erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string Namespace "I"
        descriptor AcademicSubject "R"
        string AssessmentTitle "R"
        bool AdaptiveAssessment "O"
        descriptor AssessedGradeLevel "OC"
        descriptor AssessmentCategory "O"
        string AssessmentFamily "O"
        string AssessmentForm "O"
        common AssessmentIdentificationCode "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentPeriod "OC"
        common AssessmentScore "OC"
        integer AssessmentVersion "O"
        common ContentStandard "O"
        reference EducationOrganization "O"
        descriptor Language "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        descriptor PlatformType "OC"
        date RevisionDate "O"
        choice SectionOrProgramChoice "O"
    }
    AssessmentAdministration {
        reference AssigningEducationOrganization "I"
		reference Assessment "I"
		string AdministrationIdentifier "I"
        common AssessmentAdministrationPeriod "OC"
        reference AssessmentBatteryPart "OC"
    }
    AssessmentAdministrationParticipation {
        reference AssessmentAdministration "I"
        reference ParticipatingEducationOrganization "I"
        common AdministrationPointOfContact "OC"
    }
    AssessmentBatteryPart {
        reference Assessment "I"
        string AssessmentBatteryPartName "I"
        reference ObjectiveAssessment "OC"
    }
    ObjectiveAssessment {
        reference Assessment "I"
        string IdentificationCode "I"
        descriptor AcademicSubject "O"
        reference AssessmentItem "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentScore "OC"
        string Description "O"
        reference LearningStandard "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        reference ParentObjectiveAssessment "OC"
        percent PercentOfAssessment "O"
    }
    StudentAssessmentRegistration {
        reference AssessmentAdministration "I"
        reference StudentDemographic "I"
        reference StudentSchoolAssociation "R"
        descriptor AssessmentAccommodation "OC"
        common AssessmentCustomization "OC"
        descriptor AssessmentGradeLevel "O"
        descriptor PlatformType "O"
        reference ReportingEducationOrganization "O"
        reference ScheduledStudentEducationOrganizationAssessmentAccommodation "O"
        reference TestingEducationOrganization "O"
    }
    StudentAssessmentRegistrationBatteryPartAssociation {
        reference StudentAssessmentRegistration "I"
		reference AssessmentBatteryPart "I"
        descriptor Accommodation "OC"
    }
    StudentEducationOrganizationAssessmentAccommodation {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor GeneralAccommodation "OC"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentDemographic {
		reference Student "I"
        reference EducationOrganization "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor LimitedEnglishProficiency "O"
        descriptor Race "OC"
        descriptor Sex "O"
        common StudentCharacteristic "OC"
        descriptor SupporterMilitaryConnection "O"
        descriptor TribalAffiliation "OC"
    }
    StudentSchoolAssociation {
        reference Student "I"
        reference School "I"
		date EntryDate "I"
        descriptor EntryGradeLevel "R"
        reference AlternativeGraduationPlan "OC"
        reference Calendar "O"
        enumeration ClassOfSchoolYear "O"
        descriptor EducationPlan "OC"
        bool EmployedWhileEnrolled "O"
        descriptor EnrollmentType "O"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        decimal FullTimeEquivalency "O"
        reference GraduationPlan "O"
        descriptor NextYearGradeLevel "O"
        reference NextYearSchool "O"
        bool PrimarySchool "O"
        bool RepeatGradeIndicator "O"
        descriptor ResidencyStatus "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        bool SchoolChoiceTransfer "O"
        enumeration SchoolYear "O"
        bool TermCompletionIndicator "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        reference EducationServiceCenter "O"
        descriptor FederalLocaleCode "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference StateEducationAgency "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    School ||--|| EducationOrganization : "IsA"
    School ||--|| LocalEducationAgency : "HasAssociated"
    LocalEducationAgency ||--|| EducationOrganization : "IsA"
    AssessmentBatteryPart }o--|| Assessment : "HasAssociated"
    AssessmentBatteryPart }o--o{ ObjectiveAssessment : "HasAssociated"
    ObjectiveAssessment }o--|| Assessment : "HasAssociated"
    AssessmentAdministration }o--o{ AssessmentBatteryPart : "HasAssociated"
    AssessmentAdministration }o--|| EducationOrganization : "HasAssociated"
    AssessmentAdministration }o--|| Assessment : "HasAssociated"
    AssessmentAdministrationParticipation }o--|| AssessmentAdministration : "HasAssociated"
    AssessmentAdministrationParticipation }o--|| EducationOrganization : "HasAssociated"
    StudentAssessmentRegistration }o--|| AssessmentAdministration : "HasAssociated"
    StudentAssessmentRegistration }o--|| StudentSchoolAssociation : "HasAssociated"
    StudentAssessmentRegistration }o--|| EducationOrganization : "HasAssociated"
    StudentAssessmentRegistration }o--o| StudentEducationOrganizationAssessmentAccommodation : "HasAssociated"
    StudentAssessmentRegistrationBatteryPartAssociation }o--|| StudentAssessmentRegistration : "HasAssociated"
    StudentAssessmentRegistrationBatteryPartAssociation }o--|| AssessmentBatteryPart : "HasAssociated"
    StudentEducationOrganizationAssessmentAccommodation }o--|| Student : "HasAssociated"
    StudentEducationOrganizationAssessmentAccommodation }o--|| EducationOrganization : "HasAssociated"
    StudentSchoolAssociation }o--|| Student : "HasAssociated"
    StudentSchoolAssociation }o--|| School : "HasAssociated"
    StudentDemographic }o--|| EducationOrganization : "HasAssociated"
    StudentDemographic }o--|| Student : "HasAssociated"
    StudentDemographic ||--}o StudentAssessmentRegistration : "HasAssociated"
