erDiagram
    Session {
        reference School "I"
        enumeration SchoolYear "I"
        string SessionName "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference AcademicWeek "OC"
        reference GradingPeriod "OC"
    }
    GradingPeriod {
        descriptor GradingPeriod "I"
        string GradingPeriodName "I"
        reference School "I"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        integer TotalInstructionalDays "R"
        integer PeriodSequence "O"
    }
    AcademicWeek {
        reference School "I"
        string WeekIdentifier "I"
        date BeginDate "R"
        date EndDate "R"
        integer TotalInstructionalDays "R"
    }
    Calendar {
        string CalendarCode "I"
        reference School "I"
        enumeration SchoolYear "I"
        descriptor CalendarType "R"
        descriptor GradeLevel "OC"
    }
    CalendarDate {
        reference Calendar "I"
        date Date "I"
        descriptor CalendarEvent "RC"
    }
    StudentSchoolAssociation {
        date EntryDate "I"
        reference School "I"
        reference Student "I"
        descriptor EntryGradeLevel "R"
        reference AlternativeGraduationPlan "OC"
        reference Calendar "O"
        enumeration ClassOfSchoolYear "O"
        descriptor EducationPlan "OC"
        bool EmployedWhileEnrolled "O"
        descriptor EnrollmentType "O"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        decimal FullTimeEquivalency "O"
        reference GraduationPlan "O"
        descriptor NextYearGradeLevel "O"
        reference NextYearSchool "O"
        bool PrimarySchool "O"
        bool RepeatGradeIndicator "O"
        descriptor ResidencyStatus "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        bool SchoolChoiceTransfer "O"
        enumeration SchoolYear "O"
        bool TermCompletionIndicator "O"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    Session }o--o{ AcademicWeek : "HasAssociated"
    Session }o--|| School : "HasAssociated"
    Session }o--o{ GradingPeriod : "HasAssociated"
    GradingPeriod }o--|| School : "HasAssociated"
    CalendarDate }o--|| Calendar : "HasAssociated"
    Calendar }o--|| School : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    School ||--|| EducationOrganization : "IsA"
    StudentSchoolAssociation }o--o| Calendar : "HasAssociated"
    StudentSchoolAssociation }o--|| School : "HasAssociated"
    StudentSchoolAssociation }o--|| Student : "HasAssociated"