erDiagram
    Student {
    }
    StudentHealth {
    }
    EducationOrganization {
    }
    StudentHealth ||--o{ Student : "has associated"
    StudentHealth ||--o{ EducationOrganization : "has associated"
