erDiagram
    Student {
    }
    StudentHealth {
    }
    EducationOrganization {
    }
    StudentHealth }o--|| Student : "HasAssociated"
    StudentHealth }o--|| EducationOrganization : "HasAssociated"
