erDiagram
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    Session {
        reference School "I"
        enumeration SchoolYear "I"
        string SessionName "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference AcademicWeek "OC"
        reference GradingPeriod "OC"
    }
    Course {
        string CourseCode "I"
        reference EducationOrganization "I"
        common CourseIdentificationCode "RC"
        string CourseTitle "R"
        integer NumberOfParts "R"
        descriptor AcademicSubject "OC"
        descriptor CareerPathway "O"
        descriptor CompetencyLevel "OC"
        descriptor CourseDefinedBy "O"
        string CourseDescription "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseLevelCharacteristic "OC"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        reference LearningStandard "OC"
        integer MaxCompletionsForCredit "O"
        common MaximumAvailableCredits "O"
        common MinimumAvailableCredits "O"
        descriptor OfferedGradeLevel "OC"
        integer TimeRequiredForCompletion "O"
    }
    CourseOffering {
        string LocalCourseCode "I"
        reference School "I"
        reference Session "I"
        reference Course "R"
        descriptor CourseLevelCharacteristic "OC"
        descriptor CurriculumUsed "OC"
        integer InstructionalTimePlanned "O"
        string LocalCourseTitle "O"
        descriptor OfferedGradeLevel "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        descriptor AcademicSubject "RC"
        common ContentStandard "R"
        string Description "R"
        descriptor GradeLevel "RC"
        string Namespace "R"
        string CourseTitle "O"
        descriptor LearningStandardCategory "O"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        descriptor LearningStandardScope "O"
        reference ParentLearningStandard "O"
        string SuccessCriteria "O"
        string URI "O"
    }

    Session }o--|| School : "HasAssociated"
    CourseOffering }o--|| School : "HasAssociated"
    CourseOffering }o--|| Session : "HasAssociated"
    CourseOffering }o--|| Course : "HasAssociated"
    Course }o--|| EducationOrganization : "HasAssociated"
    Course }o--o{ LearningStandard : "HasAssociated"
    LearningStandard }o--o| LearningStandard : "HasFunctionalComponent"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    School ||--|| EducationOrganization : "IsA"
