---
config:
  layout: fixed
  flowchart: 
    wrappingWidth: 300
---
flowchart TB
    managedDescriptors["<b>managedDescriptors</b><br>C: NamespaceBased<br>R: NoFurtherAuthorizationRequired<br>U: NamespaceBased<br>D: NamespaceBased"] --> accommodationDescriptor["<b>accommodationDescriptor</b><br>C | R | U | D"] & assessmentPeriodDescriptor["<b>assessmentPeriodDescriptor</b><br>C | R | U | D"] & competencyLevelDescriptor["<b>competencyLevelDescriptor</b><br>C | R | U | D"] & diagnosisDescriptor["<b>diagnosisDescriptor</b><br>C | R | U | D"] & performanceLevelDescriptor["<b>performanceLevelDescriptor</b><br>C | R | U | D"]