erDiagram
    DisciplineIncident {
        string IncidentIdentifier "I"
        reference School "I"
        date IncidentDate "R"
        common Behavior "OC"
        string CaseNumber "O"
        common DisciplineIncidentExternalParticipant "OC"
        currency IncidentCost "O"
        string IncidentDescription "O"
        descriptor IncidentLocation "O"
        time IncidentTime "O"
        bool ReportedToLawEnforcement "O"
        descriptor ReporterDescription "O"
        string ReporterName "O"
        descriptor Weapon "OC"
    }
    DisciplineAction {
        string DisciplineActionIdentifier "I"
        date DisciplineDate "I"
        reference Student "I"
        descriptor Discipline "RC"
        reference ResponsibilitySchool "R"
        reference StudentDisciplineIncidentBehaviorAssociation "RC"
        decimal ActualDisciplineActionLength "O"
        reference AssignmentSchool "O"
        decimal DisciplineActionLength "O"
        descriptor DisciplineActionLengthDifferenceReason "O"
        bool IEPPlacementMeetingIndicator "O"
        bool RelatedToZeroTolerancePolicy "O"
        reference Staff "OC"
    }
    StaffDisciplineIncidentAssociation {
        reference DisciplineIncident "I"
        reference Staff "I"
        descriptor DisciplineIncidentParticipationCode "RC"
    }
    StudentDisciplineIncidentBehaviorAssociation {
        descriptor Behavior "I"
        reference DisciplineIncident "I"
        reference Student "I"
        string BehaviorDetailedDescription "O"
        descriptor DisciplineIncidentParticipationCode "OC"
        descriptor Weapon "OC"
    }
    StudentDisciplineIncidentNonOffenderAssociation {
        reference DisciplineIncident "I"
        reference Student "I"
        descriptor DisciplineIncidentParticipationCode "OC"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        date BirthDate "O"
        reference Credential "OC"
        reference EducatorPreparationProgram "OC"
        common EducatorResearch "O"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        string LoginId "O"
        reference OpenStaffPosition "O"
        common OtherName "OC"
        reference Person "O"
        common Recognition "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    Student }o--o{ School : "HasAssociated"
    Student }o--o{ DisciplineIncident : "ParticipatesIn"
    DisciplineAction }o--|| Student : "HasAssociated"
    DisciplineAction }o--o{ StudentDisciplineIncidentBehaviorAssociation : "HasAssociated"
    DisciplineAction }o--o{ Staff : "HasAssociated"
    DisciplineAction }o--|| School : "HasAssociated"
    DisciplineAction }o--o| School : "HasCausalRelationship"
    DisciplineIncident }o--|| School : "HasAssociated"
    DisciplineIncident ||..o{ StaffDisciplineIncidentAssociation : "ParticipatesIn"
    Staff ||..o{ StaffDisciplineIncidentAssociation : "ParticipatesIn"
    Staff }o--o{ DisciplineIncident : "ParticipatesIn"
    StudentDisciplineIncidentBehaviorAssociation }o..|| DisciplineIncident : "ParticipatesIn"
    StudentDisciplineIncidentBehaviorAssociation }o..|| Student : "ParticipatesIn"
    StudentDisciplineIncidentNonOffenderAssociation }o..|| DisciplineIncident : "ParticipatesIn"
    StudentDisciplineIncidentNonOffenderAssociation }o..|| Student : "ParticipatesIn"
    Staff }o--o{ School : "HasAssociated"
