
erDiagram
    Program {
    }
    Staff {
    }
    GeneralStudentProgramAssociation["GeneralStudentProgram<br/>Association"] {
    }
    StaffProgramAssociation {
    }
    Section {
    }
    StudentSectionAssociation {
    }
    Student {
    }
    EducationOrganization {
    }
    StudentSectionAttendanceEvent["StudentSection<br/>AttendanceEvent"] {
    }
    StudentSchoolAttendanceEvent["StudentSchool<br/>AttendanceEvent"] {
    }
    StudentProgramAttendanceEvent["StudentProgram<br/>AttendanceEvent"] {
    }
    StudentSpecialEducationProgramEligibilityAssociation["StudentSpecial<br/>EducationProgram<br/>EligibilityAssociation"] {
    }
    School {
    }
    EducationOrganization }o--o{ Program : "IsDirectProviderOf"
    EducationOrganization ||--o{ Program : "HasAssociated"
    EducationOrganization ||..o{ GeneralStudentProgramAssociation : "HasAssociated"
    EducationOrganization ||..|| School : "IsA"
    Student }o--o{ Program : "ParticipatesIn"
    Program }o--o{ Staff : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    Section }|--|| School : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    Staff }o--o{ School : "HasAssociated"
    Program ||..o{ GeneralStudentProgramAssociation : "HasAssociated"
    Program ||..o{ StaffProgramAssociation : "HasAssociated"
    Staff ||..o{ StaffProgramAssociation : "HasAssociated"
    Staff }o--o{ Section : "HasAssociated"
    Student ||..o{ StudentSectionAssociation : "ParticipatesIn"
    Section ||..o{ StudentSectionAssociation : "ParticipatesIn"
    Student }o--o{ Section : "ParticipatesIn"
    Student ||..o{ StudentSpecialEducationProgramEligibilityAssociation : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Student : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Section : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| School : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| Student : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| EducationOrganization : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Program : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Student : "HasAssociated"
