erDiagram
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        reference LearningStandard "OC"
        descriptor ProgramCharacteristic "OC"
        string ProgramId "O"
        descriptor ProgramSponsor "OC"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        date BirthDate "O"
        reference Credential "OC"
        reference EducatorPreparationProgram "OC"
        common EducatorResearch "O"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        string LoginId "O"
        reference OpenStaffPosition "O"
        common OtherName "OC"
        reference Person "O"
        common Recognition "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    GeneralStudentProgramAssociation {     
        reference Student "I"
		reference Program "I"
		reference EducationOrganization "I"     
		date BeginDate "I"
        date EndDate "O"
        common ProgramParticipationStatus "OC"
        descriptor ReasonExited "O"
        bool ServedOutsideOfRegularSession "O"
    }
    StaffProgramAssociation {
        reference Staff "I"
		reference Program "I"
		date BeginDate "I"
        date EndDate "O"
        bool StudentRecordAccess "O"
    }
    Section {
        string SectionIdentifier "I"
		reference CourseOffering "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    StudentSectionAssociation {
        reference Student "I"
		reference Section "I"
		date BeginDate "I"
        descriptor AttemptStatus "O"
        common DualCredit "O"
        date EndDate "O"
        bool HomeroomIndicator "O"
        reference Program "OC"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    StudentSectionAttendanceEvent {
        reference Student "I"
		reference Section "I"
        common AttendanceEvent "R"
        time ArrivalTime "O"
        reference ClassPeriod "OC"
        time DepartureTime "O"
        integer SectionAttendanceDuration "O"
    }
    StudentSchoolAttendanceEvent {
        reference Student "I" 
		reference School "I"
        reference Session "I"
        common AttendanceEvent "R"
        time ArrivalTime "O"
        time DepartureTime "O"
        integer SchoolAttendanceDuration "O"
    }
    StudentProgramAttendanceEvent {
        reference Student "I"
		reference EducationOrganization "I"
		reference Program "I"
        common AttendanceEvent "R"
        integer ProgramAttendanceDuration "O"
    }
    StudentSpecialEducationProgramEligibilityAssociation {
        reference EducationOrganization "I"
		reference Student "I"
		reference Program "I"
		date ConsentToEvaluationReceivedDate "I"
        descriptor IDEAPart "R"
        date ConsentToEvaluationDate "O"
        date EligibilityConferenceDate "O"
        descriptor EligibilityDelayReason "O"
        date EligibilityDeterminationDate "O"
        date EligibilityEvaluationDate "O"
        descriptor EligibilityEvaluationType "O"
        bool EvaluationCompleteIndicator "O"
        integer EvaluationDelayDays "O"
        descriptor EvaluationDelayReason "O"
        string EvaluationLateReason "O"
        bool IDEAIndicator "O"
        date OriginalECIServicesDate "O"
        date TransitionConferenceDate "O"
        date TransitionNotificationDate "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    EducationOrganization }o--o{ Program : "IsDirectProviderOf"
    EducationOrganization ||--o{ Program : "HasAssociated"
    EducationOrganization ||..o{ GeneralStudentProgramAssociation : "HasAssociated"
    EducationOrganization ||..|| School : "IsA"
    Student }o--o{ Program : "ParticipatesIn"
    Program }o--o{ Staff : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    Section }|--|| School : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    Staff }o--o{ School : "HasAssociated"
    Program ||..o{ GeneralStudentProgramAssociation : "HasAssociated"
    Program ||..o{ StaffProgramAssociation : "HasAssociated"
    Staff ||..o{ StaffProgramAssociation : "HasAssociated"
    Staff }o--o{ Section : "HasAssociated"
    Student ||..o{ StudentSectionAssociation : "ParticipatesIn"
    Section ||..o{ StudentSectionAssociation : "ParticipatesIn"
    Student }o--o{ Section : "ParticipatesIn"
    Student ||..o{ StudentSpecialEducationProgramEligibilityAssociation : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Student : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Section : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| School : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| Student : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| EducationOrganization : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Program : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Student : "HasAssociated"
