erDiagram
    Program {
    }
    Student {
    }
    EducationOrganization {
    }
    GeneralStudentProgramAssociation["GeneralStudent<br/>ProgramAssociation"] {
    }
    StudentCTEProgramAssociation {
    }
    StudentHomelessProgramAssociation ["StudentHomeless<br/>ProgramAssociation"] {
    }
    StudentLanguageInstructionProgramAssociation["StudentLanguageInstruction<br/>ProgramAssociation"] {
    }
    StudentMigrantEducationProgramAssociation["StudentMigrant<br/>EducationProgram<br/>Association"] {
    }
    StudentNeglectedOrDelinquentProgramAssociation["StudentNeglectedOr<br/>DelinquentProgram<br/>Association"] {
    }
    StudentProgramAssociation {
    }
    StudentSchoolFoodServiceProgramAssociation["StudentSchoolFood<br/>ServiceProgramAssociation"] {
    }
    StudentSpecialEducationProgramAssociation["StudentSpecialEducation<br/>ProgramAssociation"] {
    }
    StudentTitleIPartAProgramAssociation["StudentTitleIPartA<br/>ProgramAssociation"] {
    }
    StudentSpecialEducationProgramEligibilityAssociation["StudentSpecialEducation<br/>ProgramEligibility<br/>Association"] {
    }
    StudentSection504ProgramAssociation["StudentSection<br/>504ProgramAssociation"] {
    }
    EducationOrganization ||--o{ Program : "HasAssociated"
    EducationOrganization }o--o{ Program : "IsDirectProviderOf"
    Student ||..o{ GeneralStudentProgramAssociation : "ParticipatesIn"
    Program ||..o{ GeneralStudentProgramAssociation : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn IsEvaluated"
    GeneralStudentProgramAssociation }o--|| EducationOrganization : "HasAssociated"
    Student ||..o{ StudentSpecialEducationProgramEligibilityAssociation : "IsEvaluated"
    Program ||..o{ StudentSpecialEducationProgramEligibilityAssociation : "IsEvaluated"
    StudentSpecialEducationProgramEligibilityAssociation }o--|| EducationOrganization : "HasAssociated"
    StudentCTEProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentHomelessProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentLanguageInstructionProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentMigrantEducationProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentNeglectedOrDelinquentProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentSchoolFoodServiceProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentSpecialEducationProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentTitleIPartAProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
    StudentSection504ProgramAssociation ||--|| GeneralStudentProgramAssociation : "IsA"
