---
title: EducatorPreparationProgram
config:
  layout: elk
---
erDiagram
    Candidate {
    }
    CandidateIdentificationCode {
    }
    EducatorPreparationProgram {
    }
    FieldworkExperience {
    }
    CandidateEducatorPreparationProgramAssociation {
    }
    CandidateRelationshipToStaffAssociation {
    }
    StaffEducatorPreparationProgramAssociation {
    }
    Person {
    }
    Staff {
    }
    EducationOrganization {
    }
    Section {
    }
    Candidate ||--o{ Person : "has associated"
    Staff ||--o{ Person : "has associated"
    Candidate ||--o{ EducatorPreparationProgram : "has associated"
    CandidateEducatorPreparationProgramAssociation ||--o{ Candidate : "has associated"
    CandidateEducatorPreparationProgramAssociation ||--o{ EducatorPreparationProgram : "has associated"
    Staff ||--o{ Candidate : "has associated"
    CandidateRelationshipToStaffAssociation ||--o{ Candidate : "has associated"
    CandidateRelationshipToStaffAssociation ||--o{ Staff : "has associated"
    StaffEducatorPreparationProgramAssociation ||--o{ Staff : "has associated"
    StaffEducatorPreparationProgramAssociation ||--o{ EducatorPreparationProgram : "has associated"
    EducationOrganization ||--o{ EducatorPreparationProgram : "has associated"
    Staff ||--o{ EducationOrganization : "has associated"
    FieldworkExperience ||--o{ EducatorPreparationProgram : "has associated"
    FieldworkExperience ||--o{ Section : "has associated"
    CandidateIdentificationCode ||--o{ Candidate : "has associated"
    CandidateIdentificationCode ||--o{ EducationOrganization : "has associated"
    EducationOrganization ||--o{ EducationOrganization : "has associated"
