erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentSchoolAttendanceEvent {
        reference School "I"
        reference Session "I"
        reference Student "I"
        common AttendanceEvent "R"
        time ArrivalTime "O"
        time DepartureTime "O"
        integer SchoolAttendanceDuration "O"
    }
    StudentSectionAttendanceEvent {
        reference Section "I"
        reference Student "I"
        common AttendanceEvent "R"
        time ArrivalTime "O"
        reference ClassPeriod "OC"
        time DepartureTime "O"
        integer SectionAttendanceDuration "O"
    }
    StudentProgramAttendanceEvent {
        reference EducationOrganization "I"
        reference Program "I"
        reference Student "I"
        common AttendanceEvent "R"
        integer ProgramAttendanceDuration "O"
    }
    StudentSectionAssociation {
        date BeginDate "I"
        reference Section "I"
        reference Student "I"
        descriptor AttemptStatus "O"
        common DualCredit "O"
        date EndDate "O"
        bool HomeroomIndicator "O"
        reference Program "OC"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
    }
    GeneralStudentProgramAssociation {
        date BeginDate "I"
        reference EducationOrganization "I"
        reference Program "I"
        reference Student "I"
        date EndDate "O"
        common ProgramParticipationStatus "OC"
        descriptor ReasonExited "O"
        bool ServedOutsideOfRegularSession "O"
    }
    SectionAttendanceTakenEvent {
        reference CalendarDate "I"
        reference Section "I"
        date EventDate "R"
        reference Staff "O"
    }
    Session {
        reference School "I"
        enumeration SchoolYear "I"
        string SessionName "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference AcademicWeek "OC"
        reference GradingPeriod "OC"
    }
    Section {
        reference CourseOffering "I"
        string SectionIdentifier "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        reference LearningStandard "OC"
        descriptor ProgramCharacteristic "OC"
        string ProgramId "O"
        descriptor ProgramSponsor "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        date BirthDate "O"
        reference Credential "OC"
        reference EducatorPreparationProgram "OC"
        common EducatorResearch "O"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        string LoginId "O"
        reference OpenStaffPosition "O"
        common OtherName "OC"
        reference Person "O"
        common Recognition "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    Session }o--|| School : "HasAssociated"
    Section }|--o| School : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    SectionAttendanceTakenEvent }o--o| Staff : "HasAssociated"
    SectionAttendanceTakenEvent }o--|| Section : "HasAssociated"
    Staff }o--o{ School : "HasAssociated"
    Staff }o--o{ Section : "HasAssociated"
    Program }o--o{ Staff : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Program : "HasAssociated"
    StudentProgramAttendanceEvent }o--|| Student : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| Session : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| School : "HasAssociated"
    StudentSchoolAttendanceEvent }o--|| Student : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Section : "HasAssociated"
    StudentSectionAttendanceEvent }o--|| Student : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    Student }o--o| Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"
    GeneralStudentProgramAssociation }o..|| Student : "ParticipatesIn"
    GeneralStudentProgramAssociation }o..|| Program : "ParticipatesIn"
    StudentSectionAssociation }o--|| Student : "ParticipatesIn"
    StudentSectionAssociation }o--|| Section : "ParticipatesIn"
