erDiagram
    InterventionStudy {
        reference EducationOrganization "I"
        string InterventionStudyIdentificationCode "I"
        descriptor DeliveryMethod "R"
        descriptor InterventionClass "R"
        reference InterventionPrescription "R"
        integer Participants "R"
        descriptor AppropriateGradeLevel "OC"
        descriptor AppropriateSex "OC"
        common EducationContentSource "O"
        common InterventionEffectiveness "OC"
        descriptor PopulationServed "OC"
        descriptor StateAbbreviation "OC"
    }
    EducationContent {
        string ContentIdentifier "I"
        choice LearningResourceChoice "R"
        string Namespace "R"
        currency Cost "O"
        descriptor CostRate "O"
    }
    InterventionPrescription {
        reference EducationOrganization "I"
        string InterventionPrescriptionIdentificationCode "I"
        descriptor DeliveryMethod "R"
        common EducationContentSource "R"
        descriptor InterventionClass "R"
        descriptor AppropriateGradeLevel "OC"
        descriptor AppropriateSex "OC"
        descriptor Diagnosis "OC"
        integer MaxDosage "O"
        integer MinDosage "O"
        string Namespace "O"
        descriptor PopulationServed "OC"
    }
    Intervention {
        reference EducationOrganization "I"
        string InterventionIdentificationCode "I"
        date BeginDate "R"
        descriptor DeliveryMethod "R"
        common EducationContentSource "R"
        descriptor InterventionClass "R"
        descriptor AppropriateGradeLevel "OC"
        descriptor AppropriateSex "OC"
        descriptor Diagnosis "OC"
        date EndDate "O"
        reference InterventionPrescription "OC"
        integer MaxDosage "O"
        common MeetingTime "OC"
        integer MinDosage "O"
        string Namespace "O"
        descriptor PopulationServed "OC"
        reference Staff "OC"
    }
    EducationOrganizationInterventionPrescriptionAssociation {
        reference EducationOrganization "I"
        reference InterventionPrescription "I"
        date BeginDate "O"
        date EndDate "O"
    }
    StudentInterventionAssociation {
        reference Intervention "I"
        reference Student "I"
        reference Cohort "O"
        string DiagnosticStatement "O"
        integer Dosage "O"
        common InterventionEffectiveness "OC"
    }
    StudentInterventionAttendanceEvent {
        reference Intervention "I"
        reference Student "I"
        common AttendanceEvent "R"
        integer InterventionDuration "O"
    }
    StudentCohortAssociation {
        date BeginDate "I"
        reference Cohort "I"
        reference Student "I"
        date EndDate "O"
        reference Section "OC"
    }
    Cohort {
        string CohortIdentifier "I"
        reference EducationOrganization "I"
        descriptor CohortType "R"
        descriptor AcademicSubject "O"
        string CohortDescription "O"
        descriptor CohortScope "O"
        reference Program "OC"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        date BirthDate "O"
        reference Credential "OC"
        reference EducatorPreparationProgram "OC"
        common EducatorResearch "O"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        string LoginId "O"
        reference OpenStaffPosition "O"
        common OtherName "OC"
        reference Person "O"
        common Recognition "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    Intervention }o--o{ InterventionPrescription : "HasAssociated"
    Intervention }o--o{ EducationContent : "HasFunctionalComponent"
    Intervention }o--|| EducationOrganization : "HasAssociated"
    Intervention }o--o{ Staff : "HasAssociated"
    Student }o--o{ Intervention : "HasAssociated"
    StudentInterventionAssociation }o..|| Student : "HasAssociated"
    StudentInterventionAssociation }o..|| Intervention : "HasAssociated"
    InterventionPrescription }o--o{ EducationContent : "HasFunctionalComponent"
    InterventionPrescription }o--|| EducationOrganization : "HasAssociated"
    InterventionStudy }o--|| InterventionPrescription : "HasAssociated"
    InterventionStudy }o--|| EducationOrganization : "HasAssociated"
    EducationOrganization ||--o{ EducationOrganizationInterventionPrescriptionAssociation : "HasAssociated"
    InterventionPrescription ||--o{ EducationOrganizationInterventionPrescriptionAssociation : "HasAssociated"  
    StudentInterventionAssociation }o--o| Cohort : "HasAssociated"
    StudentInterventionAttendanceEvent }o--|| Student : "HasAssociated"
    StudentInterventionAttendanceEvent }o--|| Intervention : "HasAssociated"
    StudentCohortAssociation }o--|| Student : "HasAssociated"
    StudentCohortAssociation }o--|| Cohort : "HasAssociated"
    Cohort }o--|| EducationOrganization : "HasAssociated"
    Cohort }o--o{ Student : "HasAssociated"
    Cohort }o--o{ Staff : "HasAssociated"
    Staff }o--o{ EducationOrganization : "HasAssociated"
    Staff }o--o{ EducationOrganization : "ProvidesServiceTo"
