erDiagram
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        date BirthDate "O"
        reference Credential "OC"
        reference EducatorPreparationProgram "OC"
        common EducatorResearch "O"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        string LoginId "O"
        reference OpenStaffPosition "O"
        common OtherName "OC"
        reference Person "O"
        common Recognition "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    StaffIdentificationCode {
        reference EducationOrganization "I"
        reference Staff "I"
        descriptor StaffIdentificationSystem "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    StaffDirectory {
        reference EducationOrganization "I"
        reference Staff "I"
        common Address "OC"
        common ElectronicMail "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
    }
    StaffDemographic {
        reference EducationOrganization "I"
        reference Staff "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor Race "OC"
        descriptor Sex "O"
        descriptor TribalAffiliation "OC"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    Credential {
        string CredentialIdentifier "I"
        descriptor StateOfIssueStateAbbreviation "I"
        descriptor CredentialType "R"
        date IssuanceDate "R"
        string Namespace "R"
        descriptor AcademicSubject "OC"
        bool BoardCertificationIndicator "O"
        reference Certification "O"
        descriptor CertificationRoute "O"
        string CertificationTitle "O"
        string CredentialEndorsement "OC"
        descriptor CredentialField "O"
        descriptor CredentialStatus "O"
        date CredentialStatusDate "O"
        descriptor EducatorRole "O"
        date EffectiveDate "O"
        date ExpirationDate "O"
        descriptor GradeLevel "OC"
        reference Person "O"
        reference StudentAcademicRecord "OC"
        descriptor TeachingCredential "O"
        descriptor TeachingCredentialBasis "O"
    }
    StaffAbsenceEvent {
        descriptor AbsenceEventCategory "I"
        date EventDate "I"
        reference Staff "I"
        string AbsenceEventReason "O"
        decimal HoursAbsent "O"
    }
    StaffLeave {
        date BeginDate "I"
        reference Staff "I"
        descriptor StaffLeaveEventCategory "I"
        date EndDate "O"
        string Reason "O"
        bool SubstituteAssigned "O"
    }
    StaffEducationOrganizationEmploymentAssociation {
        reference EducationOrganization "I"
        descriptor EmploymentStatus "I"
        reference Staff "I"
        common EmploymentPeriod "R"
        currency AnnualWage "O"
        common BackgroundCheck "OC"
        reference Credential "O"
        string Department "O"
        decimal FullTimeEquivalency "O"
        currency HourlyWage "O"
        descriptor LengthOfContract "O"
        date OfferDate "O"
        date ProbationCompleteDate "O"
        common Salary "O"
        common Seniority "OC"
        bool Tenured "O"
        bool TenureTrack "O"
    }
    StaffEducationOrganizationAssignmentAssociation {
        date BeginDate "I"
        reference EducationOrganization "I"
        reference Staff "I"
        descriptor StaffClassification "I"
        reference Credential "O"
        date EndDate "O"
        decimal FullTimeEquivalency "O"
        integer OrderOfAssignment "O"
        string PositionTitle "O"
        reference StaffEducationOrganizationEmploymentAssociation "O"
        decimal YearsOfExperienceAtCurrentEducationOrganization "O"
    }
    StaffSchoolAssociation {
        descriptor ProgramAssignment "I"
        reference School "I"
        reference Staff "I"
        descriptor AcademicSubject "OC"
        reference Calendar "O"
        descriptor GradeLevel "OC"
        enumeration SchoolYear "O"
    }
    OpenStaffPosition {
        reference EducationOrganization "I"
        string RequisitionNumber "I"
        date DatePosted "R"
        descriptor EmploymentStatus "R"
        descriptor StaffClassification "R"
        descriptor AcademicSubject "OC"
        date DatePostingRemoved "O"
        decimal FullTimeEquivalency "O"
        descriptor FundingSource "O"
        bool HighNeedAcademicSubject "O"
        descriptor InstructionalGradeLevel "OC"
        bool IsActive "O"
        decimal MaxSalary "O"
        decimal MinSalary "O"
        descriptor OpenStaffPositionReason "O"
        string PositionControlNumber "O"
        string PositionTitle "O"
        descriptor PostingResult "O"
        descriptor ProgramAssignment "O"
        enumeration SchoolYear "O"
        descriptor Term "O"
        decimal TotalBudgeted "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    EducationServiceCenter {
        integer EducationServiceCenterId "I"
        reference StateEducationAgency "O"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        reference EducationServiceCenter "O"
        descriptor FederalLocaleCode "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference StateEducationAgency "O"
    }
    StateEducationAgency {
        integer StateEducationAgencyId "I"
        descriptor FederalLocaleCode "O"
        common StateEducationAgencyAccountability "OC"
        common StateEducationAgencyFederalFunds "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    EducationServiceCenter }o--o| StateEducationAgency : "IsOrganizationComponentOf"
    LocalEducationAgency }o--o| EducationServiceCenter : "IsOrganizationComponentOf"
    LocalEducationAgency }o--o| LocalEducationAgency : "IsOrganizationComponentOf"
    School }o--o| LocalEducationAgency : "IsOrganizationComponentOf"
    Staff }o--o{ School : "HasAssociated"
    Staff }o--o{ Credential : "HasAssociated"
    Staff }o--o| Person : "HasAssociated"
    Staff }o--o{ EducationOrganization : "ProvidesServicesTo"
    Staff }o--o{ EducationOrganization : "HasAssociated"
    StaffAbsenceEvent }o--|| Staff : "HasAssociated"
    StaffEducationOrganizationAssignmentAssociation |o--o| StaffEducationOrganizationEmploymentAssociation : "HasAssociated"
    OpenStaffPosition }o--|| EducationOrganization : "HasAssociated"
    LocalEducationAgency }o--o| StateEducationAgency : "IsOrganizationComponentOf"
    StaffLeave }o--|| Staff : "HasAssociated"
    StaffEducationOrganizationAssignmentAssociation }o--o| Credential : "IsBasedOn"
    StaffEducationOrganizationEmploymentAssociation }o--o| Credential : "IsBasedOn"
    EducationOrganization ||--o{ StaffDirectory : "HasAssociated"
    EducationOrganization ||--o{ StaffDemographic : "HasAssociated"
    EducationOrganization ||--o{ StaffIdentificationCode : "HasAssociated"
    StaffDirectory }o--|| Staff : "HasAssociated"
    StaffIdentificationCode }o--|| Staff : "HasAssociated"
    StaffDemographic }o--|| Staff : "HasAssociated"
    EducationOrganization ||--|| StateEducationAgency : "IsA"
    EducationOrganization ||--|| EducationServiceCenter : "IsA"
    EducationOrganization ||--|| LocalEducationAgency : "IsA"
    EducationOrganization ||--|| School : "IsA"
    StaffEducationOrganizationEmploymentAssociation }o..|| Staff : "HasAssociated"
    StaffEducationOrganizationEmploymentAssociation }o..|| EducationOrganization : "HasAssociated"
    StaffEducationOrganizationAssignmentAssociation }o..|| Staff: "ProvidesServicesTo"
    StaffEducationOrganizationAssignmentAssociation }o..|| EducationOrganization: "ProvidesServicesTo"
    StaffSchoolAssociation }o..|| Staff : "HasAssociated"
    StaffSchoolAssociation }o..|| School : "HasAssociated"
