erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentAssessment {
        string StudentAssessmentIdentifier "I"
        reference Student "I"
		reference Assessment "I"
        enumeration SchoolYear "R"
        descriptor Accommodation "OC"
        datetime AdministrationDate "O"
        datetime AdministrationEndDate "O"
        descriptor AdministrationEnvironment "O"
        descriptor AdministrationLanguage "O"
        descriptor AssessedGradeLevel "O"
        integer AssessedMinutes "O"
        common AssessmentPeriod "O"
        descriptor EventCircumstance "O"
        string EventDescription "O"
        common PerformanceLevel "OC"
        descriptor PlatformType "O"
        descriptor ReasonNotTested "O"
        reference ReportedSchool "O"
        string ReportedSchoolIdentifier "O"
        descriptor RetestIndicator "O"
        common ScoreResult "OC"
        string SerialNumber "O"
        common StudentAssessmentIndicator "OC"
        common StudentAssessmentItem "OC"
        common StudentObjectiveAssessment "OC"
        descriptor WhenAssessedGradeLevel "O"
    }
    StudentAssessment }o--|| Student : "HasAssociated"
