erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string Namespace "I"
        descriptor AcademicSubject "R"
        string AssessmentTitle "R"
        bool AdaptiveAssessment "O"
        descriptor AssessedGradeLevel "OC"
        descriptor AssessmentCategory "O"
        string AssessmentFamily "O"
        string AssessmentForm "O"
        common AssessmentIdentificationCode "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentPeriod "OC"
        common AssessmentScore "OC"
        integer AssessmentVersion "O"
        common ContentStandard "O"
        reference EducationOrganization "O"
        descriptor Language "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        descriptor PlatformType "OC"
        date RevisionDate "O"
        choice SectionOrProgramChoice "O"
    }
    StudentAssessment {
        string StudentAssessmentIdentifier "I"
		reference Assessment "I"
        reference Student "I"
        enumeration SchoolYear "R"
        descriptor Accommodation "OC"
        datetime AdministrationDate "O"
        datetime AdministrationEndDate "O"
        descriptor AdministrationEnvironment "O"
        descriptor AdministrationLanguage "O"
        descriptor AssessedGradeLevel "O"
        integer AssessedMinutes "O"
        common AssessmentPeriod "O"
        descriptor EventCircumstance "O"
        string EventDescription "O"
        common PerformanceLevel "OC"
        descriptor PlatformType "O"
        descriptor ReasonNotTested "O"
        reference ReportedSchool "O"
        string ReportedSchoolIdentifier "O"
        descriptor RetestIndicator "O"
        common ScoreResult "OC"
        string SerialNumber "O"
        common StudentAssessmentIndicator "OC"
        common StudentAssessmentItem "OC"
        common StudentObjectiveAssessment "OC"
        descriptor WhenAssessedGradeLevel "O"
    }
    ObjectiveAssessment {
        string IdentificationCode "I"
		reference Assessment "I"
        descriptor AcademicSubject "O"
        reference AssessmentItem "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentScore "OC"
        string Description "O"
        reference LearningStandard "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        reference ParentObjectiveAssessment "OC"
        percent PercentOfAssessment "O"
    }
    AssessmentItem {
        string IdentificationCode "I"
        reference Assessment "I"
		descriptor AssessmentItemCategory "O"
        string AssessmentItemURI "O"
        duration ExpectedTimeAssessed "O"
        string ItemText "O"
        reference LearningStandard "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        common PossibleResponse "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        descriptor AcademicSubject "RC"
        common ContentStandard "R"
        string Description "R"
        descriptor GradeLevel "RC"
        string Namespace "R"
        string CourseTitle "O"
        descriptor LearningStandardCategory "O"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        descriptor LearningStandardScope "O"
        reference ParentLearningStandard "O"
        string SuccessCriteria "O"
        string URI "O"
    }
    LearningStandardEquivalenceAssociation {
        reference SourceLearningStandard "I"
        reference TargetLearningStandard "I"
        string Namespace "I"
		date EffectiveDate "O"
        descriptor LearningStandardEquivalenceStrength "O"
        string LearningStandardEquivalenceStrengthDescription "O"
    }
    AssessmentScoreRangeLearningStandard {
        reference Assessment "I"
        string ScoreRangeId "I"
        reference LearningStandard "RC"
        string MaximumScore "R"
        string MinimumScore "R"
        descriptor AssessmentReportingMethod "O"
        reference ObjectiveAssessment "O"
    }
    StudentAssessmentEducationOrganizationAssociation {
        reference StudentAssessment "I"
		reference EducationOrganization "I"
        descriptor EducationOrganizationAssociationType "I"
        enumeration SchoolYear "O"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    Section {
        string SectionIdentifier "I"
		reference CourseOffering "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        reference LearningStandard "OC"
        descriptor ProgramCharacteristic "OC"
        string ProgramId "O"
        descriptor ProgramSponsor "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    StudentAssessment }o--|| Student : "HasAssociated"
    StudentAssessment }o--|| Assessment : "HasAssociated"
    StudentAssessmentEducationOrganizationAssociation }o..|| StudentAssessment : "HasAssociated"
    StudentAssessmentEducationOrganizationAssociation }o..|| EducationOrganization : "HasAssociated"
    StudentAssessment }o--o| School : "HasAssociated"
    Assessment }o--o| EducationOrganization : "HasAssociated"
    Assessment }o--o{ Section : "HasAssociated"
    Assessment }o--o{ Program : "HasAssociated"
    ObjectiveAssessment }o--|| Assessment : "HasAssociated"
    ObjectiveAssessment }o--o{ ObjectiveAssessment : "HasFunctionalComponent"
    ObjectiveAssessment }o--o{ AssessmentItem : "HasFunctionalComponent"
    ObjectiveAssessment }o--o{ LearningStandard : "HasAssociated"
    AssessmentItem }o--o{ LearningStandard : "HasAssociated"
    AssessmentItem }o--|| Assessment : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--|{ LearningStandard : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--|| Assessment : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--o| ObjectiveAssessment : "HasAssociated"
    LearningStandardEquivalenceAssociation }o..|| LearningStandard : "HasAssociatedEquivalence"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    LearningStandard ||--o{ LearningStandard : "HasFunctionalComponent"
    Program }o--o{ LearningStandard : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"