erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string Namespace "I"
        descriptor AcademicSubject "R"
        string AssessmentTitle "R"
        bool AdaptiveAssessment "O"
        descriptor AssessedGradeLevel "OC"
        descriptor AssessmentCategory "O"
        string AssessmentFamily "O"
        string AssessmentForm "O"
        common AssessmentIdentificationCode "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentPeriod "OC"
        common AssessmentScore "OC"
        integer AssessmentVersion "O"
        common ContentStandard "O"
        reference EducationOrganization "O"
        descriptor Language "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        descriptor PlatformType "OC"
        date RevisionDate "O"
        choice SectionOrProgramChoice "O"
    }
    ObjectiveAssessment {
        string IdentificationCode "I"
		reference Assessment "I"
        descriptor AcademicSubject "O"
        reference AssessmentItem "OC"
        common AssessmentPerformanceLevel "OC"
        common AssessmentScore "OC"
        string Description "O"
        reference LearningStandard "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        reference ParentObjectiveAssessment "OC"
        percent PercentOfAssessment "O"
    }
    AssessmentItem {
        string IdentificationCode "I"
		reference Assessment "I"
        descriptor AssessmentItemCategory "O"
        string AssessmentItemURI "O"
        duration ExpectedTimeAssessed "O"
        string ItemText "O"
        reference LearningStandard "OC"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        common PossibleResponse "OC"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    Section {
        string SectionIdentifier "I"
		reference CourseOffering "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        reference LearningStandard "OC"
        descriptor ProgramCharacteristic "OC"
        string ProgramId "O"
        descriptor ProgramSponsor "OC"
    }
    ObjectiveAssessment }o--o{ ObjectiveAssessment : "HasFunctionalComponent"
    ObjectiveAssessment }o--o{ AssessmentItem : "HasFunctionalComponent"
    Assessment ||--o{ ObjectiveAssessment : "HasAssociated"
    Assessment ||--o{ AssessmentItem : "HasAssociated"
    Assessment }o--o| EducationOrganization : "HasAssociated"
    Assessment }o--o{ Section : "HasAssociated"
    Assessment }o--o{ Program : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
