erDiagram
    Assessment {
    }
    StudentAssessment {
    }
    ObjectiveAssessment {
    }
    AssessmentItem {
    }
    LearningStandard {
    }
    LearningStandardEquivalenceAssociation {
    }
    AssessmentScoreRangeLearningStandard {
    }
    StudentAssessmentEducationOrganizationAssociation {
    }
    Student {
    }
    EducationOrganization {
    }
    Section {
    }
    Program {
    }
    School {
    }
    StudentAssessment }o--|| Student : "HasAssociated"
    StudentAssessment }o--|| Assessment : "HasAssociated"
    StudentAssessmentEducationOrganizationAssociation }o..|| StudentAssessment : "HasAssociated"
    StudentAssessmentEducationOrganizationAssociation }o..|| EducationOrganization : "HasAssociated"
    StudentAssessment }o--o| School : "HasAssociated"
    Assessment }o--o| EducationOrganization : "HasAssociated"
    Assessment }o--o{ Section : "HasAssociated"
    Assessment }o--o{ Program : "HasAssociated"
    ObjectiveAssessment }o--|| Assessment : "HasAssociated"
    ObjectiveAssessment }o--o{ ObjectiveAssessment : "HasFunctionalComponent"
    ObjectiveAssessment }o--o{ AssessmentItem : "HasFunctionalComponent"
    ObjectiveAssessment }o--o{ LearningStandard : "HasAssociated"
    AssessmentItem }o--o{ LearningStandard : "HasAssociated"
    AssessmentItem }o--|| Assessment : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--|{ LearningStandard : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--|| Assessment : "HasAssociated"
    AssessmentScoreRangeLearningStandard }o--o| ObjectiveAssessment : "HasAssociated"
    LearningStandardEquivalenceAssociation }o..|| LearningStandard : "HasAssociatedEquivalence"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    LearningStandard ||--o{ LearningStandard : "HasFunctionalComponent"
    Program }o--o{ LearningStandard : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"
