erDiagram
    LearningStandard {
    }
    LearningStandardEquivalenceAssociation {
    }
    LearningStandard ||--o{ LearningStandard : "hasFunctionalComponent"
    LearningStandardEquivalenceAssociation }o..|| LearningStandard : "hasAssociatedEquivalence"
    LearningStandard }o--o{ LearningStandard : "hasAssociatedEquivalence"
