erDiagram
 StudentIEP {
     reference EducationOrganization "I"
     date IEPFinalizedDate "I"
     reference Student "I"
     string StudentIEPIdentifier "I"
     date IEPBeginDate "R"
     date IEPEndDate "R"
     descriptor IEPStatus "R"
     descriptor Accommodation "OC"
     common Disability "OC"
     reference IDEAEvent "OC"
     date IEPAmendedDate "O"
     bool MedicallyFragile "O"
     bool MultiplyDisabled "O"
     descriptor ReasonExited "O"
     decimal SchoolHoursPerWeek "O"
     decimal SpecialEducationHoursPerWeek "O"
     descriptor SpecialEducationSetting "O"
 }

 IDEAEvent {
     reference EducationOrganization "I"
     string IDEAEventIdentifier "I"
     descriptor IDEAEventType "I"
     reference Student "I"
     date BeginDate "R"
     date EndDate "O"
     descriptor EventCompliance "O"
     string EventNarrative "O"
     descriptor EventReason "O"
 }

 EducationOrganization {
     integer EducationOrganizationId "I"
     descriptor EducationOrganizationCategory "RC"
     string NameOfInstitution "R"
     common Address "OC"
     common EducationOrganizationIndicator "OC"
     common InstitutionTelephone "OC"
     common InternationalAddress "OC"
     descriptor OperationalStatus "O"
     string ShortNameOfInstitution "O"
     string WebSite "O"
 }

 StudentIEPServicePrescription["StudentIEP<br/>ServicePrescription"] {
     reference StudentIEP "I"
     descriptor ServicePrescription "I"
     date ServicePrescriptionDate "I"
     date BeginDate "R"
     integer Duration "R"
     descriptor DurationInterval "R"
     date EndDate "O"
     decimal Frequency "R"
     descriptor FrequencyInterval "R"
     reference IDEAEvent "OC"
     descriptor ServiceLocationType "R"
     reference Staff "OC"
 }

 StudentIEPServiceDelivery {
     string IEPServiceDeliveryIdentifier "I"
     descriptor ServiceDelivery "I"
     date ServiceDeliveryDate "I"
     reference StudentIEP "I"
     reference IDEAEvent "OC"
     common Provider "OC"
     reference StudentIEPServicePrescription "O"
 }

 Student {
     string StudentUniqueId "I"
     common BirthData "R"
     common Name "R"
     common OtherName "OC"
     reference Person "O"
 }

 Staff {
     string StaffUniqueId "I"
     common Name "R"
     date BirthDate "O"
     reference Credential "OC"
     reference EducatorPreparationProgram "OC"
     common EducatorResearch "O"
     descriptor HighestCompletedLevelOfEducation "O"
     descriptor HighlyQualifiedAcademicSubject "OC"
     bool HighlyQualifiedTeacher "O"
     string LoginId "O"
     reference OpenStaffPosition "O"
     common OtherName "OC"
     reference Person "O"
     common Recognition "OC"
     decimal YearsOfPriorProfessionalExperience "O"
     decimal YearsOfPriorTeachingExperience "O"
 }

 StudentIEPGoal {
     string IEPGoalIdentifier "I"
     reference StudentIEP "I"
     string IEPGoalDetails "R"
     descriptor IEPGoalType "R"
     common GoalAchievementPeriod "O"
     reference IDEAEvent "OC"
 }
    IDEAEvent }o--|| EducationOrganization : "HasAssociated"
    StudentIEPServicePrescription }o--|| StudentIEP : "HasAssociated"
    StudentIEP ||--o{ StudentIEPGoal : "HasAssociated"
    StudentIEPServiceDelivery }o--|| StudentIEPServicePrescription : "HasAssociated"
    Student }|--o{ EducationOrganization : "HasAssociated"
    Student ||--o{ IDEAEvent : "HasAssociated"
    Student ||--o{ StudentIEP : "HasAssociated"
    StudentIEP }o--o{ IDEAEvent : "HasAssociated"
    Staff }o--o{ StudentIEPServicePrescription : "HasAssociated"
    StudentIEPGoal }o--o{ IDEAEvent : "HasAssociated"
    StudentIEP ||--o{ StudentIEPServiceDelivery : "HasAssociated"
    EducationOrganization ||--o{ StudentIEP : "HasAssociated"

    style StudentIEP fill:#E1BEE7,stroke:#AA00FF,color:#000000
    style IDEAEvent fill:#E1BEE7,stroke:#AA00FF,color:#000000
    style StudentIEPServicePrescription fill:#E1BEE7,stroke:#AA00FF,color:#000000
    style StudentIEPServiceDelivery fill:#E1BEE7,stroke:#AA00FF,color:#000000
    style StudentIEPGoal fill:#E1BEE7,stroke:#AA00FF,color:#000000