erDiagram
 StudentIEP {
 }

 IDEAEvent {
 }

 EducationOrganization {
 }

 StudentIEPServicePrescription["StudentIEP<br/>ServicePrescription"] {
 }

 StudentIEPServiceDelivery {
 }

 Student {
 }

 Staff {
 }

 StudentIEPGoal {
 }

  IDEAEvent }o--|| EducationOrganization : "HasAssociated"
  StudentIEPServicePrescription }o--|| StudentIEP : "HasAssociated"
  StudentIEP ||--o{ StudentIEPGoal : "HasAssociated"
  StudentIEPServiceDelivery }o--|| StudentIEPServicePrescription : "HasAssociated"
  Student }|--o{ EducationOrganization : "HasAssociated"
  Student ||--o{ IDEAEvent : "HasAssociated"
  Student ||--o{ StudentIEP : "HasAssociated"
  StudentIEP }o--o{ IDEAEvent : "HasAssociated"
  Staff }o--o{ StudentIEPServicePrescription : "HasAssociated"
  StudentIEPGoal }o--o{ IDEAEvent : "HasAssociated"
  StudentIEP ||--o{ StudentIEPServiceDelivery : "HasAssociated"
  EducationOrganization ||--o{ StudentIEP : "HasAssociated"

  style StudentIEP fill:#E1BEE7,stroke:#AA00FF,color:#000000
  style IDEAEvent fill:#E1BEE7,stroke:#AA00FF,color:#000000
  style StudentIEPServicePrescription fill:#E1BEE7,stroke:#AA00FF,color:#000000
  style StudentIEPServiceDelivery fill:#E1BEE7,stroke:#AA00FF,color:#000000
  style StudentIEPGoal fill:#E1BEE7,stroke:#AA00FF,color:#000000
