erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentIdentificationCode {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor StudentIdentificationSystem "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    StudentDirectory {
        reference EducationOrganization "I"
        reference Student "I"
        common Address "OC"
        common ElectronicMail "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
    }
    StudentDemographic {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor LimitedEnglishProficiency "O"
        descriptor Race "OC"
        descriptor Sex "O"
        common StudentCharacteristic "OC"
        descriptor SupporterMilitaryConnection "O"
        descriptor TribalAffiliation "OC"
    }
    StudentEducationOrganizationAssociation {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor BarrierToInternetAccessInResidence "O"
        common CohortYear "OC"
        common DisplacedStudent "OC"
        bool InternetAccessInResidence "O"
        descriptor InternetAccessTypeInResidence "O"
        descriptor InternetPerformanceInResidence "O"
        string LoginId "O"
        descriptor PrimaryLearningDeviceAccess "O"
        descriptor PrimaryLearningDeviceAwayFromSchool "O"
        descriptor PrimaryLearningDeviceProvider "O"
        string ProfileThumbnail "O"
        common StudentIndicator "OC"
    }
    StudentContactAssociation {
        reference Contact "I"
        reference Student "I"
        integer ContactPriority "O"
        string ContactRestrictions "O"
        bool EmergencyContactStatus "O"
        bool LegalGuardian "O"
        bool LivesWith "O"
        bool PrimaryContactStatus "O"
        descriptor Relation "O"
    }
    Contact {
        string ContactUniqueId "I"
        common Name "R"
        common Address "OC"
        common ElectronicMail "OC"
        string GenderIdentity "O"
        descriptor HighestCompletedLevelOfEducation "O"
        common InternationalAddress "OC"
        common Language "OC"
        string LoginId "O"
        common OtherName "OC"
        reference Person "O"
        descriptor Sex "O"
        common Telephone "OC"
    }
    ContactIdentificationCode {
        reference Contact "I"
        descriptor ContactIdentificationSystem "I"
        reference EducationOrganization "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    FinancialAid {
        descriptor AidType "I"
        date BeginDate "I"
        reference Student "I"
        decimal AidAmount "O"
        string AidConditionDescription "O"
        date EndDate "O"
        bool PellGrantRecipient "O"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    Student }|--o{ Contact : "HasAssociated"
    Student }|--o{ EducationOrganization : "HasAssociated"
    Student }o--o| Person : "HasAssociated"
    Contact }o--o| Person : "HasAssociated"
    EducationOrganization ||--o{ StudentDemographic : "HasAssociated"
    EducationOrganization ||--o{ StudentIdentificationCode : "HasAssociated"
    EducationOrganization ||--o{ StudentDirectory : "HasAssociated"
    StudentIdentificationCode }o--|| Student : "HasAssociated"
    StudentDemographic }o--|| Student : "HasAssociated"
    StudentDirectory }o--|| Student : "HasAssociated"
    ContactIdentificationCode }o--|| EducationOrganization : "HasAssociated"
    ContactIdentificationCode }o--|| Contact : "HasAssociated"
    FinancialAid }o--|| Student : "HasAssociated"
    StudentContactAssociation }o..|| Student : "HasAssociated"
    StudentContactAssociation }o..|| Contact : "HasAssociated"
    StudentEducationOrganizationAssociation }o--|| Student : "HasAssociated"
    StudentEducationOrganizationAssociation }o--|| EducationOrganization : "HasAssociated"
