erDiagram
    Course {
        string CourseCode "I"
        reference EducationOrganization "I"
        common CourseIdentificationCode "RC"
        string CourseTitle "R"
        integer NumberOfParts "R"
        descriptor AcademicSubject "OC"
        descriptor CareerPathway "O"
        descriptor CompetencyLevel "OC"
        descriptor CourseDefinedBy "O"
        string CourseDescription "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseLevelCharacteristic "OC"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        reference LearningStandard "OC"
        integer MaxCompletionsForCredit "O"
        common MaximumAvailableCredits "O"
        common MinimumAvailableCredits "O"
        descriptor OfferedGradeLevel "OC"
        integer TimeRequiredForCompletion "O"
    }
    LearningStandard {
        string LearningStandardId "I"
        descriptor AcademicSubject "RC"
        common ContentStandard "R"
        string Description "R"
        descriptor GradeLevel "RC"
        string Namespace "R"
        string CourseTitle "O"
        descriptor LearningStandardCategory "O"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        descriptor LearningStandardScope "O"
        reference ParentLearningStandard "O"
        string SuccessCriteria "O"
        string URI "O"
    }
    GradebookEntry {
        string GradebookEntryIdentifier "I"
        string Namespace "I"
        date DateAssigned "R"
        string SourceSectionIdentifier "R"
        string Title "R"
        string Description "O"
        date DueDate "O"
        time DueTime "O"
        descriptor GradebookEntryType "O"
        reference GradingPeriod "O"
        reference LearningStandard "OC"
        decimal MaxPoints "O"
        reference Section "O"
    }
    StudentGradebookEntry {
        reference GradebookEntry "I"
        reference Student "I"
        descriptor AssignmentLateStatus "O"
        bool AssignmentPassed "O"
        descriptor CompetencyLevel "O"
        date DateCompleted "O"
        date DateFulfilled "O"
        string DiagnosticStatement "O"
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        decimal PointsEarned "O"
        descriptor SubmissionStatus "O"
        time TimeFulfilled "O"
    }
    StudentSectionAssociation {
        date BeginDate "I"
        reference Section "I"
        reference Student "I"
        descriptor AttemptStatus "O"
        common DualCredit "O"
        date EndDate "O"
        bool HomeroomIndicator "O"
        reference Program "OC"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
    }
    Section {
        reference CourseOffering "I"
        string SectionIdentifier "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    Course }o--o{ LearningStandard : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    LearningStandard }o--o| LearningStandard : "HasFunctionalComponent"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    GradebookEntry }o--o{ LearningStandard : "HasAssociated"
    GradebookEntry }o--|| Section : "HasAssociated"
    StudentGradebookEntry }o--|| GradebookEntry : "HasAssociated"
    StudentGradebookEntry }o--|| StudentSectionAssociation : "HasAssociated"
    StudentSectionAssociation }o..|| Student : "HasAssociated"
    StudentSectionAssociation }o..|| Section : "HasAssociated"
