erDiagram
    Student {
    }
    StudentAcademicRecord {
    }
    CourseTranscript {
    }
    ReportCard {
    }
    Grade {
    }
    StudentCompetencyObjective {
    }
    StudentSectionAssociation {
    }
    GeneralStudentProgramAssociation {
    }
    GradebookEntry {
    }
    StudentGradebookEntry {
    }
    CompetencyObjective {
    }
    Course {
    }
    CourseOffering {
    }
    Section {
    }
    Program {
    }
    GradingPeriod {
    }
    Session {
    }
    LearningStandard {
    }
    EducationOrganization {
    }
    School {
    }
    School ||--o{ EducationOrganization : "has associated"
    StudentAcademicRecord ||--o{ Student : "has associated"
    StudentAcademicRecord ||--o{ EducationOrganization : "has associated"
    StudentAcademicRecord ||--o{ ReportCard : "has associated"
    CourseTranscript ||--o{ StudentAcademicRecord : "has associated"
    CourseTranscript ||--o{ Course : "has associated"
    CourseTranscript ||--o{ EducationOrganization : "has associated"
    ReportCard ||--o{ Student : "has associated"
    ReportCard ||--o{ EducationOrganization : "has associated"
    ReportCard ||--o{ GradingPeriod : "has associated"
    ReportCard ||--o{ Grade : "has associated"
    ReportCard ||--o{ StudentCompetencyObjective : "has associated"
    Grade ||--o{ GradingPeriod : "has associated"
    Grade ||--o{ StudentSectionAssociation : "has associated"
    Grade ||--o{ LearningStandard : "has associated"
    StudentCompetencyObjective ||--o{ Student : "has associated"
    StudentCompetencyObjective ||--o{ GradingPeriod : "has associated"
    StudentCompetencyObjective ||--o{ StudentSectionAssociation : "has associated"
    StudentCompetencyObjective ||--o{ GeneralStudentProgramAssociation : "has associated"
    StudentCompetencyObjective ||--o{ CompetencyObjective : "has associated"
    StudentSectionAssociation ||--o{ Student : "has associated"
    StudentGradebookEntry ||--o{ GradebookEntry : "has associated"
    StudentGradebookEntry ||--o{ StudentSectionAssociation : "has associated"
    GeneralStudentProgramAssociation ||--o{ EducationOrganization : "has associated"
    GeneralStudentProgramAssociation ||--o{ StudentGradebookEntry : "has associated"
    GradebookEntry ||--o{ Section : "has associated"
    GradebookEntry ||--o{ GradingPeriod : "has associated"
    GradebookEntry ||--o{ LearningStandard : "has associated"
    CourseOffering ||--o{ Course : "has associated"
    CourseOffering ||--o{ Session : "has associated"
    CourseOffering ||--o{ School : "has associated"
    Section ||--o{ CourseOffering : "has associated"
    Section ||--o{ Program : "has associated"
    Section ||--o{ School : "has associated"
    Course ||--o{ EducationOrganization : "has associated"
    Course ||--o{ LearningStandard : "has associated"
    Program ||--o{ EducationOrganization : "has associated"
    Program ||--o{ LearningStandard : "has associated"
    EducationOrganization ||--o{ Program : "has associated"
    CompetencyObjective ||--o{ EducationOrganization : "has associated"
    Session ||--o{ School : "has associated"
    Session ||--o{ GradingPeriod : "has associated"
    GradingPeriod ||--o{ School : "has associated"
    Student ||--o{ School : "has associated"
    Student ||--o{ Section : "has associated"
    Student ||--o{ Program : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated"
