erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentAcademicRecord {
        reference EducationOrganization "I"
        enumeration SchoolYear "I"
        reference Student "I"
        descriptor Term "I"
        common AcademicHonor "OC"
        common ClassRanking "O"
        common CumulativeAttemptedCredits "O"
        common CumulativeEarnedCredits "O"
        common Diploma "OC"
        common GradePointAverage "OC"
        date ProjectedGraduationDate "O"
        common Recognition "OC"
        reference ReportCard "OC"
        common SessionAttemptedCredits "O"
        common SessionEarnedCredits "O"
    }
    CourseTranscript {
        reference Course "I"
        descriptor CourseAttemptResult "I"
        reference StudentAcademicRecord "I"
        descriptor AcademicSubject "OC"
        common AlternativeCourseIdentificationCode "OC"
        string AlternativeCourseTitle "O"
        string AssigningOrganizationIdentificationCode "O"
        common AttemptedCredits "O"
        string CourseCatalogURL "O"
        reference CourseProgram "OC"
        descriptor CourseRepeatCode "O"
        string CourseTitle "O"
        descriptor CreditCategory "OC"
        common EarnedAdditionalCredits "OC"
        common EarnedCredits "O"
        reference ExternalEducationOrganization "O"
        string ExternalEducationOrganizationNameOfInstitution "O"
        string FinalLetterGradeEarned "O"
        decimal FinalNumericGradeEarned "O"
        descriptor MethodCreditEarned "O"
        common PartialCourseTranscriptAwards "OC"
        reference ResponsibleTeacherStaff "O"
        reference Section "OC"
        descriptor WhenTakenGradeLevel "O"
    }
    ReportCard {
        reference EducationOrganization "I"
        reference GradingPeriod "I"
        reference Student "I"
        reference Grade "OC"
        common GradePointAverage "OC"
        decimal NumberOfDaysAbsent "O"
        decimal NumberOfDaysInAttendance "O"
        integer NumberOfDaysTardy "O"
        reference StudentCompetencyObjective "OC"
    }
    Grade {
        descriptor GradeType "I"
        reference GradingPeriod "I"
        reference StudentSectionAssociation "I"
        date CurrentGradeAsOfDate "O"
        bool CurrentGradeIndicator "O"
        string DiagnosticStatement "O"
        string GradeEarnedDescription "O"
        common LearningStandardGrade "OC"
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        descriptor PerformanceBaseConversion "O"
    }
    StudentCompetencyObjective {
        reference CompetencyObjective "I"
        reference GradingPeriod "I"
        reference Student "I"
        descriptor CompetencyLevel "R"
        string DiagnosticStatement "O"
        choice StudentCompetencyObjectiveSectionOrProgramChoice "O"
    }
    StudentSectionAssociation {
        date BeginDate "I"
        reference Section "I"
        reference Student "I"
        descriptor AttemptStatus "O"
        common DualCredit "O"
        date EndDate "O"
        bool HomeroomIndicator "O"
        reference Program "OC"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
    }
    GeneralStudentProgramAssociation {
        date BeginDate "I"
        reference EducationOrganization "I"
        reference Program "I"
        reference Student "I"
        date EndDate "O"
        common ProgramParticipationStatus "OC"
        descriptor ReasonExited "O"
        bool ServedOutsideOfRegularSession "O"
    }
    GradebookEntry {
        string GradebookEntryIdentifier "I"
        string Namespace "I"
        date DateAssigned "R"
        string SourceSectionIdentifier "R"
        string Title "R"
        string Description "O"
        date DueDate "O"
        time DueTime "O"
        descriptor GradebookEntryType "O"
        reference GradingPeriod "O"
        reference LearningStandard "OC"
        decimal MaxPoints "O"
        reference Section "O"
    }
    StudentGradebookEntry {
        reference GradebookEntry "I"
        reference Student "I"
        descriptor AssignmentLateStatus "O"
        bool AssignmentPassed "O"
        descriptor CompetencyLevel "O"
        date DateCompleted "O"
        date DateFulfilled "O"
        string DiagnosticStatement "O"
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        decimal PointsEarned "O"
        descriptor SubmissionStatus "O"
        time TimeFulfilled "O"
    }
    CompetencyObjective {
        reference EducationOrganization "I"
        string Objective "I"
        descriptor ObjectiveGradeLevel "I"
        string CompetencyObjectiveId "O"
        string Description "O"
        string SuccessCriteria "O"
    }
    Course {
        string CourseCode "I"
        reference EducationOrganization "I"
        common CourseIdentificationCode "RC"
        string CourseTitle "R"
        integer NumberOfParts "R"
        descriptor AcademicSubject "OC"
        descriptor CareerPathway "O"
        descriptor CompetencyLevel "OC"
        descriptor CourseDefinedBy "O"
        string CourseDescription "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseLevelCharacteristic "OC"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        reference LearningStandard "OC"
        integer MaxCompletionsForCredit "O"
        common MaximumAvailableCredits "O"
        common MinimumAvailableCredits "O"
        descriptor OfferedGradeLevel "OC"
        integer TimeRequiredForCompletion "O"
    }
    CourseOffering {
        string LocalCourseCode "I"
        reference School "I"
        reference Session "I"
        reference Course "R"
        descriptor CourseLevelCharacteristic "OC"
        descriptor CurriculumUsed "OC"
        integer InstructionalTimePlanned "O"
        string LocalCourseTitle "O"
        descriptor OfferedGradeLevel "OC"
    }
    Section {
        reference CourseOffering "I"
        string SectionIdentifier "I"
        common AvailableCredits "O"
        reference ClassPeriod "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor EducationalEnvironment "O"
        descriptor InstructionLanguage "O"
        reference Location "O"
        reference LocationSchool "O"
        descriptor MediumOfInstruction "O"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        descriptor PopulationServed "O"
        reference Program "OC"
        descriptor SectionCharacteristic "OC"
        string SectionName "O"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        reference LearningStandard "OC"
        descriptor ProgramCharacteristic "OC"
        string ProgramId "O"
        descriptor ProgramSponsor "OC"
    }
    GradingPeriod {
        descriptor GradingPeriod "I"
        string GradingPeriodName "I"
        reference School "I"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        integer TotalInstructionalDays "R"
        integer PeriodSequence "O"
    }
    Session {
        reference School "I"
        enumeration SchoolYear "I"
        string SessionName "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference AcademicWeek "OC"
        reference GradingPeriod "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        descriptor AcademicSubject "RC"
        common ContentStandard "R"
        string Description "R"
        descriptor GradeLevel "RC"
        string Namespace "R"
        string CourseTitle "O"
        descriptor LearningStandardCategory "O"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        descriptor LearningStandardScope "O"
        reference ParentLearningStandard "O"
        string SuccessCriteria "O"
        string URI "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    EducationOrganization }o--o{ Program : "IsDirectProviderOf"
    EducationOrganization ||--|| School : "IsA"
    Course }o--|| EducationOrganization : "HasAssociated"
    Course }o--o{ LearningStandard : "HasAssociated"
    Session }o--|| School : "HasAssociated"
    CompetencyObjective }o--|| EducationOrganization : "HasAssociated"
    StudentAcademicRecord }o--|| EducationOrganization : "HasAssociated"
    StudentAcademicRecord }o--|| Student : "HasAssociated"
    StudentAcademicRecord ||--o{ ReportCard : "HasFunctionalComponent"
    ReportCard }o--|| Student : "HasAssociated"
    ReportCard ||--o{ Grade : "HasFunctionalComponent"
    ReportCard }o--o{ StudentCompetencyObjective : "HasAssociated"
    ReportCard }o--|| GradingPeriod : "HasAssociated"
    ReportCard }o--|| EducationOrganization : "HasAssociated"
    StudentCompetencyObjective }o--|| GradingPeriod : "HasAssociated"
    StudentCompetencyObjective }o--o{ StudentSectionAssociation : "HasAssociated"
    StudentCompetencyObjective }o--o{ GeneralStudentProgramAssociation : "HasAssociated"
    StudentCompetencyObjective }o--|| CompetencyObjective : "HasAssociated"
    StudentCompetencyObjective }o--|| Student : "HasAssociated"
    Program }o--|| EducationOrganization : "HasAssociated"
    Program }o--o{ LearningStandard : "HasAssociated"
    GeneralStudentProgramAssociation }o--|| EducationOrganization : "HasAssociated"
    GradebookEntry }o--o| GradingPeriod : "HasAssociated"
    GradebookEntry }o--|| Section : "HasAssociated"
    GradebookEntry }o--o{ LearningStandard : "HasAssociated"
    CourseOffering }o--|| Session : "HasAssociated"
    CourseOffering }o--|| School : "HasAssociated"
    CourseOffering }o--|| Course : "HasAssociated"
    Grade }o--|| GradingPeriod : "HasAssociated"
    Grade }o--|| StudentSectionAssociation : "HasAssociated"
    Grade }o--o{ LearningStandard : "HasAssociated"
    StudentGradebookEntry }o--|| GradebookEntry : "HasAssociated"
    StudentGradebookEntry }o--|| StudentSectionAssociation : "HasAssociated"
    CourseTranscript }o--|| StudentAcademicRecord : "HasAssociated"
    CourseTranscript }o--|| Course : "HasAssociated"
    CourseTranscript }o--o| EducationOrganization : "HasAssociatedExternal"
    Section }o--o{ Program : "HasAssociated"
    Section }|--o| School : "HasAssociated"
    Section }o--|| CourseOffering : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"
    Session }|--o{ GradingPeriod : "HasAssociated"
    GradingPeriod }o--|| School : "HasAssociated"
    LearningStandard }o--o| LearningStandard : "HasFunctionalComponent"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedPrerequisite"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    LearningStandard }o--o| LearningStandard : "HasFunctional Component"
    StudentSectionAssociation }o..|| Student : "ParticipatesIn"
    StudentSectionAssociation }o..|| Section : "ParticipatesIn"
    GeneralStudentProgramAssociation }o..|| Student : "ParticipatesIn"
    GeneralStudentProgramAssociation }o..|| Program : "ParticipatesIn"
