erDiagram
    Student {
    }
    ReportCard {
    }
    Grade {
    }
    StudentCompetencyObjective {
    }
    StudentSectionAssociation {
    }
    GeneralStudentProgramAssociation["GeneralStudent<br/>ProgramAssociation"] {
    }
    GradingPeriod {
    }
    CompetencyObjective {
    }
    Section {
    }
    Program {
    }
    LearningStandard {
    }
    EducationOrganization {
    }
    ReportCard }o--o{ StudentCompetencyObjective : "HasAssociated"
    ReportCard ||--o{ Grade : "HasFunctional Component"
    ReportCard }o--|| Student : "HasAssociated"
    ReportCard }o--|| GradingPeriod : "HasAssociated"
    ReportCard }o--|| EducationOrganization : "HasAssociated"
    Grade }o--|| GradingPeriod : "HasAssociated"
    Grade }o--|| StudentSectionAssociation : "HasAssociated"
    Grade }o--o{ LearningStandard : "HasAssociated"
    StudentCompetencyObjective }o--|| Student : "HasAssociated"
    StudentCompetencyObjective }o--o{ GeneralStudentProgramAssociation : "HasAssociated"
    StudentCompetencyObjective }o--o{ StudentSectionAssociation : "HasAssociated"
    StudentCompetencyObjective }o--|| GradingPeriod : "HasAssociated"
    StudentCompetencyObjective }o--|| CompetencyObjective : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"
    CompetencyObjective }o--|| EducationOrganization : "HasAssociated"
    Program }o--|| EducationOrganization : "HasAssociated"
    Program }o--o{ Section : "HasAssociated"
    LearningStandard }o--o| LearningStandard : "HasFunctionalComponent"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    GeneralStudentProgramAssociation }o--|| EducationOrganization : "HasAssociated"
    GeneralStudentProgramAssociation }o..|| Student : "HasAssociated"
    GeneralStudentProgramAssociation }o..|| Program : "HasAssociated"