---
title: StudentAcademicRecord-ReportCard
config:
  layout: elk
---
erDiagram
    Student {
    }
    ReportCard {
    }
    Grade {
    }
    StudentCompetencyObjective {
    }
    StudentSectionAssociation {
    }
    GeneralStudentProgramAssociation {
    }
    GradingPeriod {
    }
    CompetencyObjective {
    }
    Section {
    }
    Program {
    }
    LearningStandard {
    }
    EducationOrganization {
    }
    ReportCard ||--o{ Student : "has associated"
    ReportCard ||--o{ GradingPeriod : "has associated"
    ReportCard ||--o{ EducationOrganization : "has associated"
    ReportCard ||--o{ Grade : "has associated"
    ReportCard ||--o{ StudentCompetencyObjective : "has associated"
    Grade ||--o{ GradingPeriod : "has associated"
    Grade ||--o{ StudentSectionAssociation : "has associated"
    Grade ||--o{ LearningStandard : "has associated"
    StudentCompetencyObjective ||--o{ Student : "has associated"
    StudentCompetencyObjective ||--o{ GradingPeriod : "has associated"
    StudentCompetencyObjective ||--o{ CompetencyObjective : "has associated"
    StudentCompetencyObjective ||--o{ GeneralStudentProgramAssociation : "has associated"
    StudentCompetencyObjective ||--o{ StudentSectionAssociation : "has associated"
    StudentSectionAssociation ||--o{ Student : "has associated"
    GeneralStudentProgramAssociation ||--o{ EducationOrganization : "has associated"
    GeneralStudentProgramAssociation ||--o{ StudentSectionAssociation : "has associated"
    Student ||--o{ Section : "has associated"
    Student ||--o{ Program : "has associated"
    Section ||--o{ Program : "has associated"
    Program ||--o{ EducationOrganization : "has associated"
    CompetencyObjective ||--o{ EducationOrganization : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated"
