erDiagram
    ApplicantProfile {
    }
    Application {
    }
    ApplicationEvent {
    }
    OpenStaffPosition {
    }
    RecruitmentEvent {
    }
    RecruitmentEventAttendance {
    }
    ProfessionalDevelopmentEvent {
    }
    ProfessionalDevelopmentEventAttendance["ProfessionalDevelopment<br/>EventAttendance"] {
    }
    Person {
    }
    EducationOrganization {
    }
    Application }o--|| ApplicantProfile : "HasAssociated"
    Application }o--|| EducationOrganization : "HasAssociated"
    Application }o--o| OpenStaffPosition : "HasAssociated"
    Application }o--o{ RecruitmentEventAttendance : "HasAssociated"
    ApplicationEvent }o--|| Application : "HasAssociated"
    RecruitmentEvent }o--|| EducationOrganization : "HasAssociated"
    RecruitmentEventAttendance }o--|| RecruitmentEvent : "HasAssociated" 
    ProfessionalDevelopmentEvent ||--o{ ProfessionalDevelopmentEventAttendance : "HasAssociated"
    ProfessionalDevelopmentEventAttendance }o--|| Person : "HasAssociated"
