erDiagram
    ApplicantProfile {
        string ApplicantProfileIdentifier "I"
        common Name "R"
        common Address "OC"
        common ApplicantCharacteristic "OC"
        common BackgroundCheck "OC"
        date BirthDate "O"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string EducatorPreparationProgramName "OC"
        common ElectronicMail "OC"
        bool FirstGenerationStudent "O"
        string GenderIdentity "O"
        common GradePointAverage "OC"
        descriptor HighestCompletedLevelOfEducation "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        bool HighlyQualifiedTeacher "O"
        bool HispanicLatinoEthnicity "O"
        common InternationalAddress "OC"
        common Language "OC"
        descriptor Race "OC"
        descriptor Sex "O"
        common Telephone "OC"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
    }
    Application {
        reference ApplicantProfile "I"
        string ApplicationIdentifier "I"
        reference EducationOrganization "I"
        date ApplicationDate "R"
        descriptor ApplicationStatus "R"
        descriptor AcademicSubject "O"
        date AcceptedDate "O"
        descriptor ApplicationSource "O"
        bool CurrentEmployee "O"
        date FirstContactDate "O"
        descriptor HighNeedsAcademicSubject "O"
        descriptor HireStatus "O"
        descriptor HiringSource "O"
        reference OpenStaffPosition "O"
        reference RecruitmentEventAttendance "OC"
        common ScoreResult "OC"
        descriptor Term "OC"
        date WithdrawDate "O"
        descriptor WithdrawReason "O"
    }
    ApplicationEvent {
        reference Application "I"
        descriptor ApplicationEventType "I"
        date EventDate "I"
        integer SequenceNumber "I"
        enumeration SchoolYear "R"
        decimal ApplicationEvaluationScore "O"
        descriptor ApplicationEventResult "O"
        date EventEndDate "O"
        descriptor Term "O"
    }
    OpenStaffPosition {
        reference EducationOrganization "I"
        string RequisitionNumber "I"
        date DatePosted "R"
        descriptor EmploymentStatus "R"
        descriptor StaffClassification "R"
        descriptor AcademicSubject "OC"
        date DatePostingRemoved "O"
        decimal FullTimeEquivalency "O"
        descriptor FundingSource "O"
        bool HighNeedAcademicSubject "O"
        descriptor InstructionalGradeLevel "OC"
        bool IsActive "O"
        decimal MaxSalary "O"
        decimal MinSalary "O"
        descriptor OpenStaffPositionReason "O"
        string PositionControlNumber "O"
        string PositionTitle "O"
        descriptor PostingResult "O"
        descriptor ProgramAssignment "O"
        enumeration SchoolYear "O"
        descriptor Term "O"
        decimal TotalBudgeted "O"
    }
    RecruitmentEvent {
        reference EducationOrganization "I"
        date EventDate "I"
        string EventTitle "I"
        descriptor RecruitmentEventType "R"
        string EventDescription "O"
        string EventLocation "O"
    }
    RecruitmentEventAttendance {
        reference RecruitmentEvent "I"
        string RecruitmentEventAttendeeIdentifier "I"
        string ElectronicMailAddress "R"
        common Name "R"
        bool Applied "O"
        common CurrentPosition "O"
        common Disability "OC"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        bool Met "O"
        string Notes "O"
        integer PreScreeningRating "O"
        descriptor Race "OC"
        common RecruitmentEventAttendeeQualifications "O"
        descriptor RecruitmentEventAttendeeType "O"
        bool Referral "O"
        string ReferredBy "O"
        descriptor Sex "O"
        string SocialMediaNetworkName "O"
        string SocialMediaUserName "O"
        common Telephone "OC"
        common Touchpoint "OC"
    }
    ProfessionalDevelopmentEvent {
        string Namespace "I"
        string ProfessionalDevelopmentTitle "I"
        descriptor ProfessionalDevelopmentOfferedBy "R"
        bool MultipleSession "O"
        string ProfessionalDevelopmentReason "O"
        bool Required "O"
        integer TotalHours "O"
    }
    ProfessionalDevelopmentEventAttendance {
        date AttendanceDate "I"
        reference Person "I"
        reference ProfessionalDevelopmentEvent "I"
        descriptor AttendanceEventCategory "R"
        string AttendanceEventReason "O"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    Application }o--|| ApplicantProfile : "HasAssociated"
    Application }o--|| EducationOrganization : "HasAssociated"
    Application }o--o| OpenStaffPosition : "HasAssociated"
    Application }o--o{ RecruitmentEventAttendance : "HasAssociated"
    ApplicationEvent }o--|| Application : "HasAssociated"
    RecruitmentEvent }o--|| EducationOrganization : "HasAssociated"
    RecruitmentEventAttendance }o--|| RecruitmentEvent : "HasAssociated" 
    ProfessionalDevelopmentEvent ||--o{ ProfessionalDevelopmentEventAttendance : "HasAssociated"
    ProfessionalDevelopmentEventAttendance }o--|| Person : "HasAssociated"
