erDiagram
    Student {
    }
    EducationOrganization {
    }
    GraduationPlan {
    }
    Path {
    }
    PathPhase {
    }
    PathMilestone {
    }
    StudentPath {
    }
    StudentPathPhaseStatus {
    }
    StudentPathMilestoneStatus {
    }
    Path ||--o{ EducationOrganization : "has associated"
    Path ||--o{ GraduationPlan : "has associated"
    PathPhase ||--o{ Path : "has associated"
    PathPhase ||--o{ PathMilestone : "has associated"
    StudentPath ||--o{ Student : "has associated"
    StudentPath ||--o{ Path : "has associated"
    StudentPathPhaseStatus ||--o{ StudentPath : "has associated"
    StudentPathPhaseStatus ||--o{ PathPhase : "has associated"
    StudentPathMilestoneStatus ||--o{ StudentPath : "has associated"
    StudentPathMilestoneStatus ||--o{ PathPhase : "has associated"
    StudentPathMilestoneStatus ||--o{ PathMilestone : "has associated"
