erDiagram
    Student {
    }
    Staff {
    }
    Cohort {
    }
    StudentCohortAssociation {
    }
    StaffCohortAssociation {
    }
    StudentInterventionAssociation {
    }
    Intervention {
    }
    StudentSectionAssociation {
    }
    StaffSectionAssociation {
    }
    Program {
    }
    Section {
    }
    EducationOrganization {
    }
    Staff }o--o{ EducationOrganization : "ProvidesServicesTo"
    Staff ||--|{ EducationOrganization : "HasAssociated"
    Staff }o--o{ Section : "HasAssociated"
    StudentCohortAssociation }o--o{ Section : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    EducationOrganization }o--o{ Program : "IsDirectProviderOf"
    StudentInterventionAssociation }o--o| Cohort : "HasAssociated"
    Intervention }o--|| EducationOrganization : "HasAssociated"
    Intervention }o--o{ Staff : "HasAssociated"
    Cohort }o--o{ Program : "HasAssociated"
    Cohort }o--|| EducationOrganization : "HasAssociated"
    Cohort }o--o{ Staff : "HasAssociated"
    Cohort }o--o{ Student : "HasAssociated"
    Program }o--o{ Staff : "HasAssociated"
    Program }o--|| EducationOrganization : "HasAssociated"
    Student }o--o{ Intervention : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    Student }o--o{ Program : "ParticipatesIn"
    StudentCohortAssociation }o..|| Student : "HasAssociated"
    StudentCohortAssociation }o..|| Cohort : "HasAssociated"
    StudentInterventionAssociation }o..|| Student : "HasAssociated"
    StudentInterventionAssociation }o..|| Intervention : "HasAssociated"
    StaffSectionAssociation }o..|| Staff : "HasAssociated"
    StaffSectionAssociation }o..|| Section : "HasAssociated"
    StaffCohortAssociation }o..|| Staff : "HasAssociated"
    StaffCohortAssociation }o..|| Cohort : "HasAssociated"
