erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentSchoolAssociation {
        date EntryDate "I"
        reference School "I"
        reference Student "I"
        descriptor EntryGradeLevel "R"
        reference AlternativeGraduationPlan "OC"
        reference Calendar "O"
        enumeration ClassOfSchoolYear "O"
        descriptor EducationPlan "OC"
        bool EmployedWhileEnrolled "O"
        descriptor EnrollmentType "O"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        decimal FullTimeEquivalency "O"
        reference GraduationPlan "O"
        descriptor NextYearGradeLevel "O"
        reference NextYearSchool "O"
        bool PrimarySchool "O"
        bool RepeatGradeIndicator "O"
        descriptor ResidencyStatus "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        bool SchoolChoiceTransfer "O"
        enumeration SchoolYear "O"
        bool TermCompletionIndicator "O"
    }
    StudentAcademicRecord {
        reference EducationOrganization "I"
        enumeration SchoolYear "I"
        reference Student "I"
        descriptor Term "I"
        common AcademicHonor "OC"
        common ClassRanking "O"
        common CumulativeAttemptedCredits "O"
        common CumulativeEarnedCredits "O"
        common Diploma "OC"
        common GradePointAverage "OC"
        date ProjectedGraduationDate "O"
        common Recognition "OC"
        reference ReportCard "OC"
        common SessionAttemptedCredits "O"
        common SessionEarnedCredits "O"
    }
    GraduationPlan {
        reference EducationOrganization "I"
        descriptor GraduationPlanType "I"
        enumeration GraduationSchoolYear "I"
        common TotalRequiredCredits "R"
        common CreditsByCourse "OC"
        common CreditsByCreditCategory "OC"
        common CreditsBySubject "OC"
        bool IndividualPlan "O"
        common RequiredAssessment "OC"
        common RequiredCertification "OC"
    }
    PostSecondaryEvent {
        date EventDate "I"
        descriptor PostSecondaryEventCategory "I"
        reference Student "I"
        reference PostSecondaryInstitution "O"
    }
    PostSecondaryInstitution {
        integer PostSecondaryInstitutionId "I"
        descriptor AdministrativeFundingControl "O"
        descriptor FederalLocaleCode "O"
        descriptor MediumOfInstruction "OC"
        descriptor PostSecondaryInstitutionLevel "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    Student }o--}o EducationOrganization : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    StudentSchoolAssociation }o..|| Student : "HasAssociated"
    StudentSchoolAssociation }o..|| School : "HasAssociated"
    StudentSchoolAssociation }o--o{ GraduationPlan : "HasAssociatedAlternative"
    StudentSchoolAssociation }o--o| GraduationPlan : "HasAssociatedPrimary"
    StudentAcademicRecord }o--|| Student : "HasAssociated"
    StudentAcademicRecord }o--|| EducationOrganization : "HasAssociated"
    GraduationPlan }o--|| EducationOrganization : "HasAssociated"
    PostSecondaryEvent }o--|| Student : "HasAssociated"
    PostSecondaryEvent }o--o| PostSecondaryInstitution : "HasAssociated"
    PostSecondaryInstitution ||--|| EducationOrganization : "IsA"
    School ||--|| EducationOrganization : "IsA"
