---
title: Graduation
config:
  layout: elk
---
erDiagram
    Student {
    }
    StudentSchoolAssociation {
    }
    StudentAcademicRecord {
    }
    GraduationPlan {
    }
    PostSecondaryEvent {
    }
    PostSecondaryInstitution {
    }
    EducationOrganization {
    }
    School {
    }
    Student ||--o{ EducationOrganization : "has associated"
    Student ||--o{ School : "has associated"
    StudentSchoolAssociation ||--o{ GraduationPlan : "has associated"
    StudentAcademicRecord ||--o{ Student : "has associated"
    StudentAcademicRecord ||--o{ EducationOrganization : "has associated"
    GraduationPlan ||--o{ EducationOrganization : "has associated"
    PostSecondaryEvent ||--o{ Student : "has associated"
    PostSecondaryEvent ||--o{ StudentSchoolAssociation : "has associated"
    PostSecondaryEvent ||--o{ PostSecondaryInstitution : "has associated"
    PostSecondaryInstitution ||--o{ EducationOrganization : "has associated"
    School ||--o{ EducationOrganization : "has associated"
