---
title: Enrollment
config:
  layout: elk
---
erDiagram
    Student {
    }
    StudentDirectory {
    }
    StudentDemographic {
    }
    StudentIdentificationCode {
    }
    StudentSchoolAssociation {
    }
    StudentEducationOrganizationAssociation {
    }
    StudentEducationOrganizationResponsibilityAssociation {
    }
    GraduationPlan {
    }
    CrisisEvent {
    }
    StudentTransportation {
    }
    AccountabilityRating {
    }
    EducationOrganization {
    }
    LocalEducationAgency {
    }
    School {
    }
    StudentDirectory ||--o{ Student : "has associated"
    StudentDirectory ||--o{ EducationOrganization : "has associated"
    StudentDemographic ||--o{ Student : "has associated"
    StudentDemographic ||--o{ EducationOrganization : "has associated"
    StudentIdentificationCode ||--o{ Student : "has associated"
    StudentIdentificationCode ||--o{ EducationOrganization : "has associated"
    Student ||--o{ EducationOrganization : "has associated"
    StudentSchoolAssociation ||--o{ Student : "has associated"
    StudentSchoolAssociation ||--o{ School : "has associated"
    StudentSchoolAssociation ||--o{ GraduationPlan : "has associated"
    StudentEducationOrganizationAssociation ||--o{ Student : "has associated"
    StudentEducationOrganizationAssociation ||--o{ EducationOrganization : "has associated"
    StudentEducationOrganizationAssociation ||--o{ CrisisEvent : "has associated"
    StudentEducationOrganizationAssociation ||--o{ GraduationPlan : "has associated"
    StudentEducationOrganizationResponsibilityAssociation ||--o{ Student : "has associated"
    StudentEducationOrganizationResponsibilityAssociation ||--o{ EducationOrganization : "has associated"
    StudentTransportation ||--o{ Student : "has associated"
    StudentTransportation ||--o{ EducationOrganization : "has associated"
    GraduationPlan ||--o{ EducationOrganization : "has associated"
    AccountabilityRating ||--o{ EducationOrganization : "has associated"
    School ||--o{ EducationOrganization : "has associated"
    School ||--o{ LocalEducationAgency : "has associated"
    LocalEducationAgency ||--o{ EducationOrganization : "has associated"
    LocalEducationAgency ||--o{ LocalEducationAgency : "has associated"
