erDiagram
    Student {
        string StudentUniqueId "I"
        common BirthData "R"
        common Name "R"
        common OtherName "OC"
        reference Person "O"
    }
    StudentDirectory {
        reference EducationOrganization "I"
        reference Student "I"
        common Address "OC"
        common ElectronicMail "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
    }
    StudentDemographic {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor LimitedEnglishProficiency "O"
        descriptor Race "OC"
        descriptor Sex "O"
        common StudentCharacteristic "OC"
        descriptor SupporterMilitaryConnection "O"
        descriptor TribalAffiliation "OC"
    }
    StudentIdentificationCode {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor StudentIdentificationSystem "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    StudentSchoolAssociation {
        date EntryDate "I"
        reference School "I"
        reference Student "I"
        descriptor EntryGradeLevel "R"
        reference AlternativeGraduationPlan "OC"
        reference Calendar "O"
        enumeration ClassOfSchoolYear "O"
        descriptor EducationPlan "OC"
        bool EmployedWhileEnrolled "O"
        descriptor EnrollmentType "O"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        decimal FullTimeEquivalency "O"
        reference GraduationPlan "O"
        descriptor NextYearGradeLevel "O"
        reference NextYearSchool "O"
        bool PrimarySchool "O"
        bool RepeatGradeIndicator "O"
        descriptor ResidencyStatus "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        bool SchoolChoiceTransfer "O"
        enumeration SchoolYear "O"
        bool TermCompletionIndicator "O"
    }
    StudentEducationOrganizationAssociation {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor BarrierToInternetAccessInResidence "O"
        common CohortYear "OC"
        common DisplacedStudent "OC"
        bool InternetAccessInResidence "O"
        descriptor InternetAccessTypeInResidence "O"
        descriptor InternetPerformanceInResidence "O"
        string LoginId "O"
        descriptor PrimaryLearningDeviceAccess "O"
        descriptor PrimaryLearningDeviceAwayFromSchool "O"
        descriptor PrimaryLearningDeviceProvider "O"
        string ProfileThumbnail "O"
        common StudentIndicator "OC"
    }
    StudentEducationOrganizationResponsibilityAssociation {
        date BeginDate "I"
        reference EducationOrganization "I"
        descriptor Responsibility "I"
        reference Student "I"
        date EndDate "O"
        reference ResponsibleEducationOrganization "O new v6.1"
    }
    GraduationPlan {
        reference EducationOrganization "I"
        descriptor GraduationPlanType "I"
        enumeration GraduationSchoolYear "I"
        common TotalRequiredCredits "R"
        common CreditsByCourse "OC"
        common CreditsByCreditCategory "OC"
        common CreditsBySubject "OC"
        bool IndividualPlan "O"
        common RequiredAssessment "OC"
        common RequiredCertification "OC"
    }
    CrisisEvent {
    }
    StudentTransportation {
        reference Student "I"
        reference TransportationEducationOrganization "I"
        string SpecialAccommodationRequirements "O"
        common StudentBusDetails "O"
        descriptor TransportationPublicExpenseEligibilityType "O"
        descriptor TransportationType "O"
    }
    AccountabilityRating {
        reference EducationOrganization "I"
        string RatingTitle "I"
        enumeration SchoolYear "I"
        string Rating "R"
        date RatingDate "O"
        string RatingOrganization "O"
        string RatingProgram "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        descriptor EducationOrganizationCategory "RC"
        string NameOfInstitution "R"
        common Address "OC"
        common EducationOrganizationIndicator "OC"
        common InstitutionTelephone "OC"
        common InternationalAddress "OC"
        descriptor OperationalStatus "O"
        string ShortNameOfInstitution "O"
        string WebSite "O"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        reference EducationServiceCenter "O"
        descriptor FederalLocaleCode "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference StateEducationAgency "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor AccreditationStatus "O"
        descriptor AdministrativeFundingControl "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor CharterStatus "O"
        descriptor FederalLocaleCode "O"
        bool ImprovingSchool "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        reference PostSecondaryInstitution "O"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor TitleIPartASchoolDesignation "O"
    }
    StudentDirectory }o--|| Student : "HasAssociated"
    StudentDirectory }o--|| EducationOrganization : "HasAssociated"
    StudentDemographic }o--|| Student : "HasAssociated"
    StudentDemographic }o--|| EducationOrganization : "HasAssociated"
    StudentIdentificationCode }o--|| Student : "HasAssociated"
    StudentIdentificationCode }o--|| EducationOrganization : "HasAssociated"
    Student }o--o{ EducationOrganization : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    StudentSchoolAssociation }o..|| Student : "HasAssociated"
    StudentSchoolAssociation }o..|| School : "HasAssociated"
    StudentSchoolAssociation }o--}o GraduationPlan : "HasAssociated"
    StudentEducationOrganizationAssociation }o..|| Student : "HasAssociated"
    StudentEducationOrganizationAssociation }o..|| EducationOrganization : "HasAssociated"
    StudentEducationOrganizationAssociation }o--o{ CrisisEvent : "HasAssociated"
    StudentEducationOrganizationResponsibilityAssociation }o..|| Student : "HasAssociated"
    StudentEducationOrganizationResponsibilityAssociation }o..|| EducationOrganization : "HasAssociated"
    StudentTransportation }o--|| Student : "HasAssociated"
    StudentTransportation }o--|| EducationOrganization : "HasAssociated"
    GraduationPlan }o--|| EducationOrganization : "HasAssociated"
    AccountabilityRating }o--|| EducationOrganization : "HasAssociated"
    School ||--|| EducationOrganization : "IsA"
    School }o--o| LocalEducationAgency : "IsOrganizationalComponentOf"
    LocalEducationAgency }o--|| EducationOrganization : "IsA"
    LocalEducationAgency }o--o| LocalEducationAgency : "IsOrganizationalComponentOf"