erDiagram
    Credential {
    }
    CredentialEvent {
    }
    Certification {
    }
    CertificationExam {
    }
    CertificationExamResult {
    }
    Person {
    }
    Staff {
    }
    StudentAcademicRecord {
    }
    EducationOrganization {
    }
    StudentAssessment {
    }
    Staff }o--o| Person : "IsA"
    Staff }o--o{ EducationOrganization : "HasAssociated"
    Credential }o--o{ Staff : "HasAssociated"
    Credential }o--o| Person : "HasAssociated"
    Credential }o--o| Certification : "HasAssociated"
    Credential }o--o{ StudentAcademicRecord : "HasAssociated"
    CredentialEvent }o--|| Credential : "HasAssociated"
    Certification }o--o{ CertificationExam : "HasAssociated"
    Certification }o--o{ EducationOrganization : "HasAssociated"
    CertificationExam }o--o{ EducationOrganization : "HasAssociated"
    CertificationExamResult }o--|| CertificationExam : "HasAssociated"
    CertificationExamResult }o--|| Person : "HasAssociated"
    CertificationExamResult |o--o| StudentAssessment : "HasAssociated"
