erDiagram
    Survey {
    }
    SurveySection {
    }
    SurveyQuestion {
    }
    SurveyResponse {
    }
    SurveySectionResponse {
    }
    SurveyQuestionResponse {
    }
    SurveyProgramAssociation {
    }
    SurveyCourseAssociation {
    }
    SurveySectionAssociation {
    }
    SurveyResponseEducationOrganizationTargetAssociation["SurveyResponse<br/>EducationOrganization<br/>TargetAssociation"] {
    }
    SurveyResponseStaffTargetAssociation["SurveyResponseStaff<br/>TargetAssociation"] {
    }
    SurveySectionResponseEducationOrganizationTargetAssociation["SurveySectionResponse<br/>EducationOrganization<br/>TargetAssociation"] {
    }
    SurveySectionResponseStaffTargetAssociation["SurveySectionResponse<br/>StaffTargetAssociation"] {
    }
    Session {
    }
    Course {
    }
    Program {
    }
    Section {
    }
    Student {
    }
    Contact {
    }
    Staff {
    }
    Person {
    }
    EducationOrganization {
    }
    Survey }o--o| EducationOrganization : "HasAssociated"
    Survey }o--o| Session : "HasAssociated"
    Survey }o--o{ Program : "HasAssociated"
    Survey }o--o{ Course : "HasAssociated"
    Survey }o--o{ Section : "HasAssociated"
    SurveySection }o--|| Survey : "HasAssociated"
    SurveyQuestion }o--|| Survey : "HasAssociated"
    SurveyQuestion }o--o| SurveySection : "HasAssociated"
    SurveyResponse }o--o{ Student : "HasAssociated"
    SurveyResponse }o--o{ Staff : "HasAssociated"
    SurveyResponse }o--o{ Contact : "HasAssociated"
    SurveyResponse }o--|| Survey : "HasAssociated"
    SurveyResponse }o--|| Person : "HasAssociated"
    SurveySectionResponse }o--|| SurveyResponse : "HasAssociated"
    SurveySectionResponse }o--|| SurveySection : "HasAssociated"
    SurveyQuestionResponse }o--|| SurveyQuestion : "HasAssociated"
    SurveyQuestionResponse }o--|| SurveyResponse : "HasAssociated"
    SurveyResponse }o--o{ EducationOrganization : "HasAssociated"
    SurveySectionResponse }o--o{ EducationOrganization : "HasAssociated"
    SurveySectionResponse }o--o{ Staff : "HasAssociated"
    SurveyCourseAssociation }o..|| Survey : "HasAssociated"
    SurveyCourseAssociation }o..|| Course : "HasAssociated"
    SurveyProgramAssociation }o..|| Survey : "HasAssociated"
    SurveyProgramAssociation }o..|| Program : "HasAssociated"
    SurveySectionAssociation }o..|| Survey : "HasAssociated"
    SurveySectionAssociation }o..|| Section : "HasAssociated"
    SurveyResponseEducationOrganizationTargetAssociation }o..|| SurveyResponse : "HasAssociated"
    SurveyResponseEducationOrganizationTargetAssociation }o..|| EducationOrganization : "HasAssociated"
    SurveySectionResponseEducationOrganizationTargetAssociation }o..|| EducationOrganization : "HasAssociated"
    SurveySectionResponseEducationOrganizationTargetAssociation }o..|| SurveySectionResponse : "HasAssociated"
    SurveyResponseStaffTargetAssociation }o..|| Staff : "HasAssociated"
    SurveyResponseStaffTargetAssociation }o..|| SurveyResponse : "HasAssociated"
    SurveySectionResponseStaffTargetAssociation }o..|| Staff : "HasAssociated"
    SurveySectionResponseStaffTargetAssociation }o..|| SurveySectionResponse : "HasAssociated"
