# Original source: Docusaurus documentation

name: On Pull Request

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  scan-actions-bidi:
    name: Scan Actions, scan files for BIDI Trojan Attacks
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-config.json

  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: npm

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm ci

      # TODO: re-enable linting after existing lint has been cleaned up
      # - name: Lint markdown
      #   run: npm run lint

      - name: Test build website
        run: npm run build

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    steps:

      - name: Checkout the Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Dependency Review ("Dependabot on PR")
        if: ${{ github.event_name == 'pull_request' && !github.event.repository.fork }}
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@b7351df727350dca84cb9d725d57dcf5bc82ba26 # v3.37.1
        with:
          languages: javascript-typescript, actions

      - name: Perform CodeQL Analysis
        if: success()
        uses: github/codeql-action/analyze@b7351df727350dca84cb9d725d57dcf5bc82ba26 # v3.37.1
